language: cpp
compiler:
  - gcc
  - clang

before_install:
  - echo Getting Premake4
  - echo Current Directory is $PWD 
  - wget http://downloads.sourceforge.net/project/premake/Premake/4.4/premake-4.4-beta5-linux.tar.gz?r=http%3A%2F%2Findustriousone.com%2Fpremake%2Fdownload&ts=1413151633&use_mirror=heanet
  - tar -zxvf premake-4.4-beta5-linux.tar.gz
  - ls
  - chmod +x premake4
  - echo Current Directory is $PWD
  - cd Dependencies && ../premake4 gmake
  - cd ../Development/Tools && ../../premake4 gmake
  - cd ../DefaultProject && ../../premake4 gmake

install: true

script:
  - cd Dependencies && make config=release32
  - cd ../Development/Tools && make config=release32
  - cd ../DefaultProject && make config=release32
