language: cpp
compiler:
  - gcc
  - clang

before_install:
  - echo Getting Premake4
  - echo Current Directory is $PWD 
  - wget http://ghostdev.gamedev-pt.net/Downloads/premake4
  - chmod +x premake4
  - ldd premake4
  - echo Current Directory is $PWD
  - cd Dependencies && ../premake4 gmake
  - cd ../Development/Tools && ../../premake4 gmake
  - cd ../DefaultProject && ../../premake4 gmake

install: true

script:
  - cd Dependencies && make config=release32
  - cd ../Development/Tools && make config=release32
  - cd ../DefaultProject && make config=release32
