LOCAL_PATH := $(call my-dir)
LOCAL_PATH_MINUS_ONE_LEVEL := $(LOCAL_PATH)/../
LOCAL_PATH_DEPENDENCIES_FOLDER := $(LOCAL_PATH_MINUS_ONE_LEVEL)/../../Dependencies/

include $(CLEAR_VARS)

LOCAL_MODULE    := FlamingDependencies
LOCAL_SRC_FILES := $(LOCAL_PATH_DEPENDENCIES_FOLDER)/obj/local/$(TARGET_ARCH_ABI)/libFlamingDependencies.a

include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := sndfile
LOCAL_SRC_FILES := $(LOCAL_PATH_DEPENDENCIES_FOLDER)/Libs/Android/$(TARGET_ARCH_ABI)/libsndfile.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include

include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := openal
LOCAL_SRC_FILES := $(LOCAL_PATH_DEPENDENCIES_FOLDER)/Libs/Android/$(TARGET_ARCH_ABI)/libopenal.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include

include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := DefaultProject
LOCAL_CPP_FEATURES += exceptions
LOCAL_CPP_FEATURES += rtti

GLOBAL_INCLUDES := $(LOCAL_PATH_DEPENDENCIES_FOLDER)/Headers/ \
			$(LOCAL_PATH_DEPENDENCIES_FOLDER)/Headers/lua/ \
			$(LOCAL_PATH_DEPENDENCIES_FOLDER)/Headers/zlib/ \
			$(LOCAL_PATH_DEPENDENCIES_FOLDER)/Headers/zlib/ \
			$(LOCAL_PATH_DEPENDENCIES_FOLDER)/Source/webp/ \
			$(LOCAL_PATH_MINUS_ONE_LEVEL)/Source/ \
			$(LOCAL_PATH_MINUS_ONE_LEVEL)/../Core/

CORE_SOURCES := $(wildcard $(LOCAL_PATH_MINUS_ONE_LEVEL)/../Core/*.cpp)

LOCAL_CFLAGS := -DGL_GLEXT_PROTOTYPES -D__ANDROID__ -D__unix__ -DSFML_OPENGL_ES -DSFML_WINDOW_EXPORTS -DSFML_SYSTEM_EXPORTS -DSFML_NETWORK_EXPORTS -DSFML_GRAPHICS_EXPORTS -DSFML_AUDIO_EXPORTS -DGLEW_STATIC -DUNICODE -DFT2_BUILD_LIBRARY
LOCAL_CPP_FLAGS := -std=c++0x
LOCAL_C_INCLUDES := $(GLOBAL_INCLUDES)
LOCAL_LDLIBS := 
LOCAL_EXPORT_LDLIBS := -lEGL -llog -landroid
LOCAL_STATIC_LIBRARIES := FlamingDependencies
LOCAL_SHARED_LIBRARIES := openal sndfile

LOCAL_SRC_FILES := $(CORE_SOURCES)

#LOCAL_SHORT_COMMANDS := true
include $(BUILD_SHARED_LIBRARY)
