Flaming Torch Framework: Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType > Class Template Reference
Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType > Class Template Reference
#include <Delegate.h>
Public Types
typedef Delegate4 type
Public Member Functions
Delegate4 ()
Delegate4 (const Delegate4 &x)
template<class X , class Y >
Delegate4 (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4))
template<class X , class Y >
Delegate4 (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) const)
Delegate4 (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4))
template<class X , class Y >
void Bind (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4))
template<class X , class Y >
void Bind (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) const)
void Bind (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4))
void clear ()
bool empty () const
const DelegateMemento & GetMemento ()
operator unspecified_bool_type () const
bool operator! () const
bool operator!= (const Delegate4 &x) const
bool operator!= (StaticFunctionPtr funcptr)
RetType operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4) const
bool operator< (const Delegate4 &x) const
void operator= (const Delegate4 &x)
void operator= (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4))
bool operator== (const Delegate4 &x) const
bool operator== (StaticFunctionPtr funcptr)
bool operator> (const Delegate4 &x) const
void SetMemento (const DelegateMemento &any)
Member Typedef Documentation
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> typedef Delegate4 Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::type
Constructor & Destructor Documentation
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4 () inline
References Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::clear().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4 (const Delegate4< Param1, Param2, Param3, Param4, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4 (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4 (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4 (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) function_to_bind) inline
References Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Bind().
Member Function Documentation
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Bind (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
Referenced by Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4(), and Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator=().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Bind (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> void Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Bind (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindstaticfunc().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> void Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::clear () inline
References Gallant::DelegateMemento::clear().
Referenced by Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> bool Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::empty () const inline
Referenced by Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator unspecified_bool_type().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> const DelegateMemento& Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::GetMemento () inline
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator unspecified_bool_type () const inline
References Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::empty().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> bool Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator! () const inline
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> bool Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator!= (const Delegate4< Param1, Param2, Param3, Param4, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> bool Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator!= (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> RetType Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4) const inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureMemPtr(), and Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureThis().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> bool Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator< (const Delegate4< Param1, Param2, Param3, Param4, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> void Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator= (const Delegate4< Param1, Param2, Param3, Param4, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> void Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator= (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) function_to_bind) inline
References Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Bind().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> bool Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator== (const Delegate4< Param1, Param2, Param3, Param4, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> bool Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator== (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> bool Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator> (const Delegate4< Param1, Param2, Param3, Param4, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class Param3, class Param4, class RetType = detail::DefaultVoid> void Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::SetMemento (const DelegateMemento & any) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().