Flaming Torch Framework: SubSystem Class Reference
SubSystem Class Reference
#include <SubSystem.hpp>
Inherited by Console, FileSystemWatcher, FPSCounter, Future, GameClock, GameNetwork, Log, LuaScriptManager, PackageFileSystemManager, Profiler, RendererManager, ResourceManager, SoundManager, and SuperSmartPointerOperationCounter.
Public Member Functions
SubSystem (uint32 Priority)
virtual ~SubSystem ()
void Register ()
virtual void Shutdown (uint32 Priority)
virtual void StartUp (uint32 Priority)
virtual void Update (uint32 Priority)
Static Public Attributes
static Signal1< uint32 > OnSubsystemShutdown
static Signal1< uint32 > OnSubsystemStartUp
static Signal1< uint32 > OnSubsystemUpdate
Protected Attributes
uint32 SubsystemPriority
bool WasStarted
Constructor & Destructor Documentation
SubSystem::SubSystem (uint32 Priority) inline
virtual SubSystem::~SubSystem () inline virtual
Member Function Documentation
void SubSystem::Register () inline
References Shutdown(), StartUp(), and Update().
virtual void SubSystem::Shutdown (uint32 Priority) inline virtual
Reimplemented in FileSystemWatcher, PackageFileSystemManager, GameNetwork, LuaScriptManager, SoundManager, SuperSmartPointerOperationCounter, Log, GameClock, Profiler, Future, and FPSCounter.
Referenced by Register(), and SuperSmartPointerOperationCounter::Shutdown().
virtual void SubSystem::StartUp (uint32 Priority) inline virtual
Reimplemented in FileSystemWatcher, PackageFileSystemManager, GameNetwork, LuaScriptManager, SoundManager, Log, GameClock, SuperSmartPointerOperationCounter, Profiler, Future, and FPSCounter.
Referenced by Register(), and SuperSmartPointerOperationCounter::StartUp().
virtual void SubSystem::Update (uint32 Priority) inline virtual
Reimplemented in FileSystemWatcher, PackageFileSystemManager, GameNetwork, LuaScriptManager, SoundManager, SuperSmartPointerOperationCounter, GameClock, Profiler, Future, and FPSCounter.
Referenced by Register(), and SuperSmartPointerOperationCounter::Update().
Member Data Documentation
Signal1<uint32> SubSystem::OnSubsystemShutdown static
Signal1<uint32> SubSystem::OnSubsystemStartUp static
Signal1<uint32> SubSystem::OnSubsystemUpdate static
uint32 SubSystem::SubsystemPriority protected
bool SubSystem::WasStarted protected
Referenced by Future::Post(), and Future::PostDelayed().