Flaming Torch Framework: Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 > Class Template Reference
Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 > Class Template Reference
#include <Signal.h>
Public Types
typedef Delegate5< Param1,
Param2, Param3, Param4, Param5 > _Delegate
Public Member Functions
void Connect (_Delegate delegate)
template<class X , class Y >
void Connect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5))
template<class X , class Y >
void Connect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) const)
void Disconnect (_Delegate delegate)
template<class X , class Y >
void Disconnect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5))
template<class X , class Y >
void Disconnect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) const)
void Emit (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) const
void operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) const
Member Typedef Documentation
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 > typedef Delegate5< Param1, Param2, Param3, Param4, Param5 > Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::_Delegate
Member Function Documentation
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 > void Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Connect (_Delegate delegate) inline
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 > template<class X , class Y > void Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Connect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 > template<class X , class Y > void Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Connect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) const func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 > void Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Disconnect (_Delegate delegate) inline
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 > template<class X , class Y > void Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Disconnect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 > template<class X , class Y > void Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Disconnect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) const func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 > void Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Emit (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) const inline
Referenced by Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::operator()().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 > void Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) const inline
References Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Emit().