Flaming Torch Framework: Stream Class Reference
Stream Class Reference abstract
#include <FileSystem.hpp>
Inherited by ConstantMemoryStream, FileStream, and MemoryStream.
Public Member Functions
virtual ~Stream ()
virtual void AsBuffer (void *Data, uint32 Length)=0
std::string AsString ()
bool CopyTo (Stream *Out)
SuperSmartPointer
< StreamProcessor > GetProcessor ()
virtual uint64 Length () const =0
virtual uint64 Position () const =0
virtual bool Read (void *Data, uint32 ElementSize, uint32 Length)=0
template<typename type >
bool Read2 (type *Data, uint32 Length=1)
bool ReadFromStream (Stream *Target, uint32 Length)
virtual bool Seek (uint64 Position)=0
void SetProcessor (SuperSmartPointer< StreamProcessor > Processor)
virtual bool Write (const void *Data, uint32 ElementSize, uint32 Length)=0
template<typename type >
bool Write2 (const type *Data, uint32 Length=1)
bool WriteToStream (Stream *Target, uint32 Length)
Protected Attributes
SuperSmartPointer
< StreamProcessor > Processor
Detailed Description
Data Stream Class
Constructor & Destructor Documentation
virtual Stream::~Stream () inline virtual
Member Function Documentation
virtual void Stream::AsBuffer (void * Data, uint32 Length) pure virtual
Gets a part of the stream as a buffer
Parameters
Data the data to read from
Length the amount of bytes to read
Implemented in FileStream, ConstantMemoryStream, and MemoryStream.
std::string Stream::AsString ()
Returns
the stream as a String
bool Stream::CopyTo (Stream * Out)
Copies a Stream to another Stream
Parameters
Out the stream to write to
SuperSmartPointer<StreamProcessor> Stream::GetProcessor () inline
Gets our active stream processor
References Processor.
virtual uint64 Stream::Length () const pure virtual
Returns
the size of the stream
Implemented in FileStream, ConstantMemoryStream, and MemoryStream.
Referenced by Read2(), and Write2().
virtual uint64 Stream::Position () const pure virtual
Returns
the position in the stream
Implemented in FileStream, ConstantMemoryStream, and MemoryStream.
virtual bool Stream::Read (void * Data, uint32 ElementSize, uint32 Length) pure virtual
Reads data from a stream
Parameters
Data the data to read
ElementSize the Size of an element in the data as bytes
Length the amount of elements to read
Implemented in FileStream, ConstantMemoryStream, and MemoryStream.
Referenced by Read2().
template<typename type > bool Stream::Read2 (type * Data, uint32 Length = 1) inline
Template-specialized Read method
Parameters
Data the data to read
Length how many data elements to read
See also
Stream::Read
References Length(), and Read().
bool Stream::ReadFromStream (Stream * Target, uint32 Length)
Writes data from another stream into this stream
Parameters
Target the stream to read from
Length the amount to read from in bytes
virtual bool Stream::Seek (uint64 Position) pure virtual
Moves the stream's position
Parameters
Position the new Position
Returns
whether we were able to move
Implemented in FileStream, ConstantMemoryStream, and MemoryStream.
void Stream::SetProcessor (SuperSmartPointer< StreamProcessor > Processor) inline
Sets a new stream processor to this stream
Parameters
Processor the processor to set up
References Processor.
virtual bool Stream::Write (const void * Data, uint32 ElementSize, uint32 Length) pure virtual
Writes data to a stream
Parameters
Data the data to write
ElementSize the Size of an element in the data as bytes
Length the amount of elements to write
Implemented in FileStream, ConstantMemoryStream, and MemoryStream.
Referenced by Write2().
template<typename type > bool Stream::Write2 (const type * Data, uint32 Length = 1) inline
Template-specialized Write method
Parameters
Data the data to write
Length how many data elements to write
See also
Stream::Write
References Length(), and Write().
bool Stream::WriteToStream (Stream * Target, uint32 Length)
Writes data from this stream into another stream
Parameters
Target the stream to write to
Length the amount to write to in bytes
Member Data Documentation
SuperSmartPointer<StreamProcessor> Stream::Processor protected
Referenced by GetProcessor(), and SetProcessor().