Flaming Torch Framework: Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType > Class Template Reference
Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType > Class Template Reference
#include <Delegate.h>
Public Types
typedef Delegate6 type
Public Member Functions
Delegate6 ()
Delegate6 (const Delegate6 &x)
template<class X , class Y >
Delegate6 (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6))
template<class X , class Y >
Delegate6 (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) const)
Delegate6 (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6))
template<class X , class Y >
void Bind (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6))
template<class X , class Y >
void Bind (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) const)
void Bind (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6))
void clear ()
bool empty () const
const DelegateMemento & GetMemento ()
operator unspecified_bool_type () const
bool operator! () const
bool operator!= (const Delegate6 &x) const
bool operator!= (StaticFunctionPtr funcptr)
RetType operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) const
bool operator< (const Delegate6 &x) const
void operator= (const Delegate6 &x)
void operator= (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6))
bool operator== (const Delegate6 &x) const
bool operator== (StaticFunctionPtr funcptr)
bool operator> (const Delegate6 &x) const
void SetMemento (const DelegateMemento &any)
Member Typedef Documentation
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> typedef Delegate6 Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::type
Constructor & Destructor Documentation
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6 () inline
References Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::clear().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6 (const Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6 (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6 (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6 (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) function_to_bind) inline
References Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Bind().
Member Function Documentation
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Bind (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
Referenced by Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6(), and Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator=().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Bind (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> void Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Bind (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindstaticfunc().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> void Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::clear () inline
References Gallant::DelegateMemento::clear().
Referenced by Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> bool Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::empty () const inline
Referenced by Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator unspecified_bool_type().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> const DelegateMemento& Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::GetMemento () inline
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator unspecified_bool_type () const inline
References Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::empty().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> bool Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator! () const inline
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> bool Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator!= (const Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> bool Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator!= (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> RetType Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) const inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureMemPtr(), and Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureThis().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> bool Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator< (const Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> void Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator= (const Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> void Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator= (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) function_to_bind) inline
References Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Bind().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> bool Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator== (const Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> bool Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator== (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> bool Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator> (const Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class RetType = detail::DefaultVoid> void Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::SetMemento (const DelegateMemento & any) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().