Flaming Torch Framework: Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 > Class Template Reference
Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 > Class Template Reference
#include <Signal.h>
Public Types
typedef Delegate8< Param1,
Param2, Param3, Param4, Param5,
Param6, Param7, Param8 > _Delegate
Public Member Functions
void Connect (_Delegate delegate)
template<class X , class Y >
void Connect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8))
template<class X , class Y >
void Connect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const)
void Disconnect (_Delegate delegate)
template<class X , class Y >
void Disconnect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8))
template<class X , class Y >
void Disconnect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const)
void Emit (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const
void operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const
Member Typedef Documentation
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 > typedef Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 > Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::_Delegate
Member Function Documentation
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 > void Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Connect (_Delegate delegate) inline
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 > template<class X , class Y > void Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Connect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 > template<class X , class Y > void Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Connect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 > void Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Disconnect (_Delegate delegate) inline
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 > template<class X , class Y > void Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Disconnect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 > template<class X , class Y > void Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Disconnect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 > void Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Emit (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const inline
Referenced by Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::operator()().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 > void Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const inline
References Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Emit().