Flaming Torch Framework: Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 > Class Template Reference
Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 > Class Template Reference
#include <Signal.h>
Public Types
typedef Delegate7< Param1,
Param2, Param3, Param4, Param5,
Param6, Param7 > _Delegate
Public Member Functions
void Connect (_Delegate delegate)
template<class X , class Y >
void Connect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7))
template<class X , class Y >
void Connect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) const)
void Disconnect (_Delegate delegate)
template<class X , class Y >
void Disconnect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7))
template<class X , class Y >
void Disconnect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) const)
void Emit (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) const
void operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) const
Member Typedef Documentation
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 > typedef Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 > Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::_Delegate
Member Function Documentation
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 > void Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Connect (_Delegate delegate) inline
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 > template<class X , class Y > void Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Connect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 > template<class X , class Y > void Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Connect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) const func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 > void Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Disconnect (_Delegate delegate) inline
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 > template<class X , class Y > void Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Disconnect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 > template<class X , class Y > void Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Disconnect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) const func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 > void Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Emit (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) const inline
Referenced by Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::operator()().
template<class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 > void Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) const inline
References Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Emit().