Flaming Torch Framework: Future Class Reference
Future Class Reference
#include <Future.hpp>
Inherits SubSystem.
Public Types
typedef void(* FutureFn)(MemoryStream &Arguments)
Public Member Functions
Future ()
void Post (FutureFn Ptr, const MemoryStream &Stream=MemoryStream())
template<class Class >
void Post (Class *Instance, void(Class::*Function)(MemoryStream &Arguments), const MemoryStream &Stream=MemoryStream())
void PostDelayed (FutureFn Ptr, uint32 Delay=0, const MemoryStream &Stream=MemoryStream())
template<class Class >
void PostDelayed (Class *Instance, void(Class::*Function)(MemoryStream &Arguments), uint32 Length, const MemoryStream &Stream=MemoryStream())
void Shutdown (uint32 Priority)
void StartUp (uint32 Priority)
void Update (uint32 Priority)
Public Member Functions inherited from SubSystem
SubSystem (uint32 Priority)
virtual ~SubSystem ()
void Register ()
Static Public Attributes
static Future Instance
Static Public Attributes inherited from SubSystem
static Signal1< uint32 > OnSubsystemShutdown
static Signal1< uint32 > OnSubsystemStartUp
static Signal1< uint32 > OnSubsystemUpdate
Additional Inherited Members
Protected Attributes inherited from SubSystem
uint32 SubsystemPriority
bool WasStarted
Detailed Description
class to run code some time later
Member Typedef Documentation
typedef void(* Future::FutureFn)(MemoryStream &Arguments)
Constructor & Destructor Documentation
Future::Future () inline
Referenced by Post(), and PostDelayed().
Member Function Documentation
void Future::Post (FutureFn Ptr, const MemoryStream & Stream = MemoryStream())
Registers a function and a memory stream with arguments to be run immediately after the next frame
Parameters
Ptr the function pointer
Stream the Memory Stream
template<class Class > void Future::Post (Class * Instance, void(Class::*)(MemoryStream &Arguments) Function, const MemoryStream & Stream = MemoryStream()) inline
References Future(), Log::Instance, Log::LogErr(), and SubSystem::WasStarted.
void Future::PostDelayed (FutureFn Ptr, uint32 Delay = 0, const MemoryStream & Stream = MemoryStream())
Registers a function and a memory stream with arguments to be run a while after it is called
Parameters
Ptr the function pointer
Delay the delay in miliseconds
Stream the Memory Stream
template<class Class > void Future::PostDelayed (Class * Instance, void(Class::*)(MemoryStream &Arguments) Function, uint32 Length, const MemoryStream & Stream = MemoryStream()) inline
References Future(), Log::Instance, Log::LogErr(), and SubSystem::WasStarted.
void Future::Shutdown (uint32 Priority) virtual
Reimplemented from SubSystem.
void Future::StartUp (uint32 Priority) virtual
Reimplemented from SubSystem.
void Future::Update (uint32 Priority) virtual
Reimplemented from SubSystem.
Member Data Documentation
Future Future::Instance static