Flaming Torch Framework: ScriptedWorldStreamerCallback Class Reference
ScriptedWorldStreamerCallback Class Reference
#include <WorldStreamer.hpp>
Inherits WorldStreamerCallback.
Public Member Functions
ScriptedWorldStreamerCallback (SuperSmartPointer< LuaScript > Script)
bool ChunkNeedsLoad (const Vector3 &GlobalCoordinate)
const Vector3 & ChunkSize ()
void OnMapChunkCoordinateUpdate (WorldChunk *Chunk)
bool OnMapChunkLoad (WorldChunk *Chunk, StateCollection *State)
void OnMapChunkUnload (WorldChunk *Chunk, StateCollection *State)
Public Member Functions inherited from WorldStreamerCallback
virtual ~WorldStreamerCallback ()
Public Attributes
luabind::object ChunkCoordinateUpdateFunction
luabind::object ChunkLoadFunction
luabind::object ChunkNeedsLoadFunction
luabind::object ChunkSizeFunction
luabind::object ChunkUnloadFunction
SuperSmartPointer< LuaScript > ScriptInstance
Constructor & Destructor Documentation
ScriptedWorldStreamerCallback::ScriptedWorldStreamerCallback (SuperSmartPointer< LuaScript > Script) inline
References SuperSmartPointer< type >::Get(), and LuaScript::State.
Member Function Documentation
bool ScriptedWorldStreamerCallback::ChunkNeedsLoad (const Vector3 & GlobalCoordinate) inline virtual
Inform the streamer whether a specific chunk can be loaded
Parameters
GlobalCoordinate the glbal coordinate of this chunk
Returns
whether the map chunk can be loaded
Implements WorldStreamerCallback.
References ChunkNeedsLoadFunction, Log::Instance, and Log::LogErr().
const Vector3& ScriptedWorldStreamerCallback::ChunkSize () inline virtual
Returns
the size in pixels or units of each chunk (separately)
Implements WorldStreamerCallback.
References ChunkSizeFunction, Log::Instance, and Log::LogErr().
void ScriptedWorldStreamerCallback::OnMapChunkCoordinateUpdate (WorldChunk * Chunk) inline virtual
Updates a chunk's local coordinate
Parameters
Chunk the chunk to be updated, with the new coordinate
Implements WorldStreamerCallback.
References ChunkCoordinateUpdateFunction, Log::Instance, and Log::LogErr().
bool ScriptedWorldStreamerCallback::OnMapChunkLoad (WorldChunk * Chunk, StateCollection * State) inline virtual
Perform the loading process on this chunk
Parameters
Chunk the chunk to be loaded
State the state collection associated to the chunk
Returns
whether the map chunk was loaded
Implements WorldStreamerCallback.
References ChunkLoadFunction, Log::Instance, and Log::LogErr().
void ScriptedWorldStreamerCallback::OnMapChunkUnload (WorldChunk * Chunk, StateCollection * State) inline virtual
Perform the unload process on this chunk (like saving data)
Parameters
Chunk the chunk to be unloaded
State the state collection associated to the chunk
Implements WorldStreamerCallback.
References ChunkUnloadFunction, Log::Instance, and Log::LogErr().
Member Data Documentation
luabind::object ScriptedWorldStreamerCallback::ChunkCoordinateUpdateFunction
Referenced by OnMapChunkCoordinateUpdate().
luabind::object ScriptedWorldStreamerCallback::ChunkLoadFunction
Referenced by OnMapChunkLoad().
luabind::object ScriptedWorldStreamerCallback::ChunkNeedsLoadFunction
Referenced by ChunkNeedsLoad().
luabind::object ScriptedWorldStreamerCallback::ChunkSizeFunction
Referenced by ChunkSize().
luabind::object ScriptedWorldStreamerCallback::ChunkUnloadFunction
Referenced by OnMapChunkUnload().
SuperSmartPointer<LuaScript> ScriptedWorldStreamerCallback::ScriptInstance