Flaming Torch Framework: Gallant::Delegate1< Param1, RetType > Class Template Reference
Gallant::Delegate1< Param1, RetType > Class Template Reference
#include <Delegate.h>
Public Types
typedef Delegate1 type
Public Member Functions
Delegate1 ()
Delegate1 (const Delegate1 &x)
template<class X , class Y >
Delegate1 (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1))
template<class X , class Y >
Delegate1 (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1) const)
Delegate1 (DesiredRetType(*function_to_bind)(Param1 p1))
template<class X , class Y >
void Bind (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1))
template<class X , class Y >
void Bind (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1) const)
void Bind (DesiredRetType(*function_to_bind)(Param1 p1))
void clear ()
bool empty () const
const DelegateMemento & GetMemento ()
operator unspecified_bool_type () const
bool operator! () const
bool operator!= (const Delegate1 &x) const
bool operator!= (StaticFunctionPtr funcptr)
RetType operator() (Param1 p1) const
bool operator< (const Delegate1 &x) const
void operator= (const Delegate1 &x)
void operator= (DesiredRetType(*function_to_bind)(Param1 p1))
bool operator== (const Delegate1 &x) const
bool operator== (StaticFunctionPtr funcptr)
bool operator> (const Delegate1 &x) const
void SetMemento (const DelegateMemento &any)
Member Typedef Documentation
template<class Param1, class RetType = detail::DefaultVoid> typedef Delegate1 Gallant::Delegate1< Param1, RetType >::type
Constructor & Destructor Documentation
template<class Param1, class RetType = detail::DefaultVoid> Gallant::Delegate1< Param1, RetType >::Delegate1 () inline
References Gallant::Delegate1< Param1, RetType >::clear().
template<class Param1, class RetType = detail::DefaultVoid> Gallant::Delegate1< Param1, RetType >::Delegate1 (const Delegate1< Param1, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate1< Param1, RetType >::Delegate1 (Y * pthis, DesiredRetType(X::*)(Param1 p1) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
template<class Param1, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate1< Param1, RetType >::Delegate1 (const Y * pthis, DesiredRetType(X::*)(Param1 p1) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class RetType = detail::DefaultVoid> Gallant::Delegate1< Param1, RetType >::Delegate1 (DesiredRetType(*)(Param1 p1) function_to_bind) inline
References Gallant::Delegate1< Param1, RetType >::Bind().
Member Function Documentation
template<class Param1, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate1< Param1, RetType >::Bind (Y * pthis, DesiredRetType(X::*)(Param1 p1) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
Referenced by Gallant::Delegate1< Param1, RetType >::Delegate1(), and Gallant::Delegate1< Param1, RetType >::operator=().
template<class Param1, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate1< Param1, RetType >::Bind (const Y * pthis, DesiredRetType(X::*)(Param1 p1) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class RetType = detail::DefaultVoid> void Gallant::Delegate1< Param1, RetType >::Bind (DesiredRetType(*)(Param1 p1) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindstaticfunc().
template<class Param1, class RetType = detail::DefaultVoid> void Gallant::Delegate1< Param1, RetType >::clear () inline
References Gallant::DelegateMemento::clear().
Referenced by Gallant::Delegate1< Param1, RetType >::Delegate1().
template<class Param1, class RetType = detail::DefaultVoid> bool Gallant::Delegate1< Param1, RetType >::empty () const inline
Referenced by Gallant::Delegate1< Param1, RetType >::operator unspecified_bool_type().
template<class Param1, class RetType = detail::DefaultVoid> const DelegateMemento& Gallant::Delegate1< Param1, RetType >::GetMemento () inline
template<class Param1, class RetType = detail::DefaultVoid> Gallant::Delegate1< Param1, RetType >::operator unspecified_bool_type () const inline
References Gallant::Delegate1< Param1, RetType >::empty().
template<class Param1, class RetType = detail::DefaultVoid> bool Gallant::Delegate1< Param1, RetType >::operator! () const inline
template<class Param1, class RetType = detail::DefaultVoid> bool Gallant::Delegate1< Param1, RetType >::operator!= (const Delegate1< Param1, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class RetType = detail::DefaultVoid> bool Gallant::Delegate1< Param1, RetType >::operator!= (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class RetType = detail::DefaultVoid> RetType Gallant::Delegate1< Param1, RetType >::operator() (Param1 p1) const inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureMemPtr(), and Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureThis().
template<class Param1, class RetType = detail::DefaultVoid> bool Gallant::Delegate1< Param1, RetType >::operator< (const Delegate1< Param1, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class RetType = detail::DefaultVoid> void Gallant::Delegate1< Param1, RetType >::operator= (const Delegate1< Param1, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class RetType = detail::DefaultVoid> void Gallant::Delegate1< Param1, RetType >::operator= (DesiredRetType(*)(Param1 p1) function_to_bind) inline
References Gallant::Delegate1< Param1, RetType >::Bind().
template<class Param1, class RetType = detail::DefaultVoid> bool Gallant::Delegate1< Param1, RetType >::operator== (const Delegate1< Param1, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class RetType = detail::DefaultVoid> bool Gallant::Delegate1< Param1, RetType >::operator== (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class RetType = detail::DefaultVoid> bool Gallant::Delegate1< Param1, RetType >::operator> (const Delegate1< Param1, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class RetType = detail::DefaultVoid> void Gallant::Delegate1< Param1, RetType >::SetMemento (const DelegateMemento & any) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().