Flaming Torch Framework: Gallant::Delegate3< Param1, Param2, Param3, RetType > Class Template Reference
Gallant::Delegate3< Param1, Param2, Param3, RetType > Class Template Reference
#include <Delegate.h>
Public Types
typedef Delegate3 type
Public Member Functions
Delegate3 ()
Delegate3 (const Delegate3 &x)
template<class X , class Y >
Delegate3 (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3))
template<class X , class Y >
Delegate3 (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3) const)
Delegate3 (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3))
template<class X , class Y >
void Bind (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3))
template<class X , class Y >
void Bind (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3) const)
void Bind (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3))
void clear ()
bool empty () const
const DelegateMemento & GetMemento ()
operator unspecified_bool_type () const
bool operator! () const
bool operator!= (const Delegate3 &x) const
bool operator!= (StaticFunctionPtr funcptr)
RetType operator() (Param1 p1, Param2 p2, Param3 p3) const
bool operator< (const Delegate3 &x) const
void operator= (const Delegate3 &x)
void operator= (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3))
bool operator== (const Delegate3 &x) const
bool operator== (StaticFunctionPtr funcptr)
bool operator> (const Delegate3 &x) const
void SetMemento (const DelegateMemento &any)
Member Typedef Documentation
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> typedef Delegate3 Gallant::Delegate3< Param1, Param2, Param3, RetType >::type
Constructor & Destructor Documentation
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3 () inline
References Gallant::Delegate3< Param1, Param2, Param3, RetType >::clear().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3 (const Delegate3< Param1, Param2, Param3, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3 (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3 (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3 (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3) function_to_bind) inline
References Gallant::Delegate3< Param1, Param2, Param3, RetType >::Bind().
Member Function Documentation
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate3< Param1, Param2, Param3, RetType >::Bind (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
Referenced by Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3(), and Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator=().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate3< Param1, Param2, Param3, RetType >::Bind (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> void Gallant::Delegate3< Param1, Param2, Param3, RetType >::Bind (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindstaticfunc().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> void Gallant::Delegate3< Param1, Param2, Param3, RetType >::clear () inline
References Gallant::DelegateMemento::clear().
Referenced by Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> bool Gallant::Delegate3< Param1, Param2, Param3, RetType >::empty () const inline
Referenced by Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator unspecified_bool_type().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> const DelegateMemento& Gallant::Delegate3< Param1, Param2, Param3, RetType >::GetMemento () inline
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator unspecified_bool_type () const inline
References Gallant::Delegate3< Param1, Param2, Param3, RetType >::empty().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> bool Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator! () const inline
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> bool Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator!= (const Delegate3< Param1, Param2, Param3, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> bool Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator!= (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> RetType Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator() (Param1 p1, Param2 p2, Param3 p3) const inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureMemPtr(), and Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureThis().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> bool Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator< (const Delegate3< Param1, Param2, Param3, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> void Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator= (const Delegate3< Param1, Param2, Param3, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> void Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator= (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3) function_to_bind) inline
References Gallant::Delegate3< Param1, Param2, Param3, RetType >::Bind().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> bool Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator== (const Delegate3< Param1, Param2, Param3, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> bool Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator== (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> bool Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator> (const Delegate3< Param1, Param2, Param3, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class Param3, class RetType = detail::DefaultVoid> void Gallant::Delegate3< Param1, Param2, Param3, RetType >::SetMemento (const DelegateMemento & any) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().