Flaming Torch Framework: LuaScriptManager Class Reference
LuaScriptManager Class Reference
#include <LuaScript.hpp>
Inherits SubSystem.
Public Member Functions
LuaScriptManager ()
SuperSmartPointer< LuaScript > CreateScript (const std::string &Code, LuaLib **Libs, uint32 LibCount)
void LogError (const std::string &Message)
int32 PerformMainLoop (SuperSmartPointer< LuaScript > LoopScript)
void Shutdown (uint32 Priority)
void StartUp (uint32 Priority)
void Update (uint32 Priority)
Public Member Functions inherited from SubSystem
SubSystem (uint32 Priority)
virtual ~SubSystem ()
void Register ()
Public Attributes
SuperSmartPointer< FileStream > ErrorStream
Static Public Attributes
static LuaScriptManager Instance
Static Public Attributes inherited from SubSystem
static Signal1< uint32 > OnSubsystemShutdown
static Signal1< uint32 > OnSubsystemStartUp
static Signal1< uint32 > OnSubsystemUpdate
Friends
class LuaScript
Additional Inherited Members
Protected Attributes inherited from SubSystem
uint32 SubsystemPriority
bool WasStarted
Detailed Description
Script Manager
Constructor & Destructor Documentation
LuaScriptManager::LuaScriptManager () inline
Member Function Documentation
SuperSmartPointer<LuaScript> LuaScriptManager::CreateScript (const std::string & Code, LuaLib ** Libs, uint32 LibCount)
Creates a script
Parameters
Code the Script's code
Libs is the LuaLibs to use (FrameworkLib is not used by default)
LibCount is how many libs we are using
See also
FrameworkLib
void LuaScriptManager::LogError (const std::string & Message)
Referenced by InputCenter::ScriptedContext::OnAction(), InputCenter::ScriptedContext::OnCharacterEntered(), InputCenter::ScriptedContext::OnGainFocus(), InputCenter::ScriptedContext::OnJoystickAxis(), InputCenter::ScriptedContext::OnJoystickButton(), InputCenter::ScriptedContext::OnJoystickConnected(), InputCenter::ScriptedContext::OnJoystickDisconnected(), InputCenter::ScriptedContext::OnKey(), InputCenter::ScriptedContext::OnLoseFocus(), InputCenter::ScriptedContext::OnMouseButton(), InputCenter::ScriptedContext::OnMouseMove(), and ScriptedConsoleCommand::ScriptedMethodProxy().
int32 LuaScriptManager::PerformMainLoop (SuperSmartPointer< LuaScript > LoopScript)
Performs the Main Loop of the application from a script
Parameters
LoopScript the Script used for the main loop
Returns
0 if we succeeded, non-0 on failure
void LuaScriptManager::Shutdown (uint32 Priority) virtual
Reimplemented from SubSystem.
void LuaScriptManager::StartUp (uint32 Priority) virtual
Reimplemented from SubSystem.
void LuaScriptManager::Update (uint32 Priority) virtual
Reimplemented from SubSystem.
Friends And Related Function Documentation
friend class LuaScript friend
Member Data Documentation
SuperSmartPointer<FileStream> LuaScriptManager::ErrorStream
LuaScriptManager LuaScriptManager::Instance static
Referenced by InputCenter::ScriptedContext::OnAction(), InputCenter::ScriptedContext::OnCharacterEntered(), InputCenter::ScriptedContext::OnGainFocus(), InputCenter::ScriptedContext::OnJoystickAxis(), InputCenter::ScriptedContext::OnJoystickButton(), InputCenter::ScriptedContext::OnJoystickConnected(), InputCenter::ScriptedContext::OnJoystickDisconnected(), InputCenter::ScriptedContext::OnKey(), InputCenter::ScriptedContext::OnLoseFocus(), InputCenter::ScriptedContext::OnMouseButton(), InputCenter::ScriptedContext::OnMouseMove(), and ScriptedConsoleCommand::ScriptedMethodProxy().