Flaming Torch Framework: SuperSmartPointerOperationCounter Class Reference
SuperSmartPointerOperationCounter Class Reference
#include <SuperSmartPointer.hpp>
Inherits SubSystem.
Public Member Functions
SuperSmartPointerOperationCounter ()
void Report (bool Alloc)
void Shutdown (uint32 Priority)
void StartUp (uint32 Priority)
void Update (uint32 Priority)
Public Member Functions inherited from SubSystem
SubSystem (uint32 Priority)
virtual ~SubSystem ()
void Register ()
Public Attributes
int32 AllocCounter
int32 Counter
uint64 LastUpdateTime
Static Public Attributes
static
SuperSmartPointerOperationCounter Instance
Static Public Attributes inherited from SubSystem
static Signal1< uint32 > OnSubsystemShutdown
static Signal1< uint32 > OnSubsystemStartUp
static Signal1< uint32 > OnSubsystemUpdate
Additional Inherited Members
Protected Attributes inherited from SubSystem
uint32 SubsystemPriority
bool WasStarted
Constructor & Destructor Documentation
SuperSmartPointerOperationCounter::SuperSmartPointerOperationCounter () inline
Member Function Documentation
void SuperSmartPointerOperationCounter::Report (bool Alloc) inline
References Counter.
Referenced by SuperSmartPointer< GameServer >::Dispose(), SuperSmartPointer< GameServer >::operator SuperSmartPointer< OutType >(), SuperSmartPointer< GameServer >::Replace(), SuperSmartPointer< GameServer >::Reset(), and SuperSmartPointer< GameServer >::SuperSmartPointer().
void SuperSmartPointerOperationCounter::Shutdown (uint32 Priority) inline virtual
Reimplemented from SubSystem.
References Log::Instance, Log::LogInfo(), and SubSystem::Shutdown().
void SuperSmartPointerOperationCounter::StartUp (uint32 Priority) inline virtual
Reimplemented from SubSystem.
References Log::Instance, Log::LogInfo(), and SubSystem::StartUp().
void SuperSmartPointerOperationCounter::Update (uint32 Priority) inline virtual
Reimplemented from SubSystem.
References Log::Instance, Log::LogDebug(), and SubSystem::Update().
Member Data Documentation
int32 SuperSmartPointerOperationCounter::AllocCounter
int32 SuperSmartPointerOperationCounter::Counter
Referenced by Report().
SuperSmartPointerOperationCounter SuperSmartPointerOperationCounter::Instance static
Referenced by SuperSmartPointer< GameServer >::Dispose(), SuperSmartPointer< GameServer >::operator SuperSmartPointer< OutType >(), SuperSmartPointer< GameServer >::Replace(), SuperSmartPointer< GameServer >::Reset(), and SuperSmartPointer< GameServer >::SuperSmartPointer().
uint64 SuperSmartPointerOperationCounter::LastUpdateTime