Flaming Torch Framework: Gallant::DelegateMemento Class Reference
Gallant::DelegateMemento Class Reference
#include <Delegate.h>
Inherited by Gallant::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >, and Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >.
Public Member Functions
DelegateMemento ()
DelegateMemento (const DelegateMemento &right)
void clear ()
bool empty () const
bool IsEqual (const DelegateMemento &x) const
bool IsLess (const DelegateMemento &right) const
bool operator! () const
bool operator< (const DelegateMemento &right)
DelegateMemento & operator= (const DelegateMemento &right)
bool operator> (const DelegateMemento &right)
Protected Types
typedef void(detail::GenericClass::* GenericMemFuncType)()
Protected Member Functions
void SetMementoFrom (const DelegateMemento &right)
Protected Attributes
GenericMemFuncType m_pFunction
detail::GenericClass * m_pthis
Member Typedef Documentation
typedef void(detail::GenericClass::* Gallant::DelegateMemento::GenericMemFuncType)() protected
Constructor & Destructor Documentation
Gallant::DelegateMemento::DelegateMemento () inline
Gallant::DelegateMemento::DelegateMemento (const DelegateMemento & right) inline
Member Function Documentation
void Gallant::DelegateMemento::clear () inline
Referenced by Gallant::Delegate0< RetType >::clear(), Gallant::Delegate1< Param1, RetType >::clear(), Gallant::Delegate2< Param1, Param2, RetType >::clear(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::clear(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::clear(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::clear(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::clear(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::clear(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::clear().
bool Gallant::DelegateMemento::empty () const inline
Referenced by Gallant::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::IsEqualToStaticFuncPtr().
bool Gallant::DelegateMemento::IsEqual (const DelegateMemento & x) const inline
References m_pFunction, and m_pthis.
Referenced by Gallant::Delegate0< RetType >::operator!=(), Gallant::Delegate1< Param1, RetType >::operator!=(), Gallant::Delegate2< Param1, Param2, RetType >::operator!=(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator!=(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator!=(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator!=(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator!=(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator!=(), Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator!=(), Gallant::Delegate0< RetType >::operator==(), Gallant::Delegate1< Param1, RetType >::operator==(), Gallant::Delegate2< Param1, Param2, RetType >::operator==(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator==(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator==(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator==(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator==(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator==(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator==().
bool Gallant::DelegateMemento::IsLess (const DelegateMemento & right) const inline
References m_pFunction, and m_pthis.
Referenced by operator<(), Gallant::Delegate0< RetType >::operator<(), Gallant::Delegate1< Param1, RetType >::operator<(), Gallant::Delegate2< Param1, Param2, RetType >::operator<(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator<(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator<(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator<(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator<(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator<(), Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator<(), operator>(), Gallant::Delegate0< RetType >::operator>(), Gallant::Delegate1< Param1, RetType >::operator>(), Gallant::Delegate2< Param1, Param2, RetType >::operator>(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator>(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator>(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator>(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator>(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator>(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator>().
bool Gallant::DelegateMemento::operator! () const inline
bool Gallant::DelegateMemento::operator< (const DelegateMemento & right) inline
References IsLess().
DelegateMemento& Gallant::DelegateMemento::operator= (const DelegateMemento & right) inline
References SetMementoFrom().
bool Gallant::DelegateMemento::operator> (const DelegateMemento & right) inline
References IsLess().
void Gallant::DelegateMemento::SetMementoFrom (const DelegateMemento & right) inline protected
References m_pFunction, and m_pthis.
Referenced by Gallant::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::CopyFrom(), and operator=().
Member Data Documentation
GenericMemFuncType Gallant::DelegateMemento::m_pFunction protected
Referenced by Gallant::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::GetClosureMemPtr(), IsEqual(), IsLess(), and SetMementoFrom().
detail::GenericClass* Gallant::DelegateMemento::m_pthis protected
Referenced by Gallant::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::GetClosureThis(), IsEqual(), IsLess(), and SetMementoFrom().