Flaming Torch Framework: Log Class Reference
Log Class Reference
#include <Log.hpp>
Inherits SubSystem.
Public Member Functions
Log ()
void HideTag (const std::string &Tag)
void LogDebug (const char *Tag, const char *Format,...)
void LogErr (const char *Tag, const char *Format,...)
void LogInfo (const char *Tag, const char *Format,...)
void LogWarn (const char *Tag, const char *Format,...)
void Shutdown (uint32 Priority)
void StartUp (uint32 Priority)
Public Member Functions inherited from SubSystem
SubSystem (uint32 Priority)
virtual ~SubSystem ()
void Register ()
virtual void Update (uint32 Priority)
Public Attributes
std::string FolderName
bool PrintTime
Static Public Attributes
static Log Instance
Static Public Attributes inherited from SubSystem
static Signal1< uint32 > OnSubsystemShutdown
static Signal1< uint32 > OnSubsystemStartUp
static Signal1< uint32 > OnSubsystemUpdate
Additional Inherited Members
Protected Attributes inherited from SubSystem
uint32 SubsystemPriority
bool WasStarted
Detailed Description
Logging class
Constructor & Destructor Documentation
Log::Log () inline
Member Function Documentation
void Log::HideTag (const std::string & Tag)
Hides a Tag from being logged
void Log::LogDebug (const char * Tag, const char * Format, ...)
Log a Debug event
Parameters
Tag the event's Tag
Format the event's Format (same as Printf)
Referenced by SuperSmartPointer< GameServer >::Dispose(), SuperSmartPointer< GameServer >::operator=(), SuperSmartPointer< GameServer >::Replace(), SuperSmartPointer< GameServer >::Reset(), SuperSmartPointer< GameServer >::SuperSmartPointer(), SuperSmartPointerOperationCounter::Update(), and SuperSmartPointer< GameServer >::~SuperSmartPointer().
void Log::LogErr (const char * Tag, const char * Format, ...)
Log an Error event
Parameters
Tag the event's Tag
Format the event's Format (same as Printf)
Referenced by SuperSmartPointerCollisionManager::Add(), ScriptedWorldStreamerCallback::ChunkNeedsLoad(), ScriptedWorldStreamerCallback::ChunkSize(), ScriptedWorldStreamerCallback::OnMapChunkCoordinateUpdate(), ScriptedWorldStreamerCallback::OnMapChunkLoad(), ScriptedWorldStreamerCallback::OnMapChunkUnload(), Future::Post(), and Future::PostDelayed().
void Log::LogInfo (const char * Tag, const char * Format, ...)
Log an Information event
Parameters
Tag the event's Tag
Format the event's Format (same as Printf)
Referenced by SuperSmartPointerOperationCounter::Shutdown(), and SuperSmartPointerOperationCounter::StartUp().
void Log::LogWarn (const char * Tag, const char * Format, ...)
Log a Warning event
Parameters
Tag the event's Tag
Format the event's Format (same as Printf)
void Log::Shutdown (uint32 Priority) virtual
Reimplemented from SubSystem.
void Log::StartUp (uint32 Priority) virtual
Reimplemented from SubSystem.
Member Data Documentation
std::string Log::FolderName
Folder Name Override Used to override the default folder name Leave empty to use the normal log folder name
Log Log::Instance static
Referenced by SuperSmartPointerCollisionManager::Add(), ScriptedWorldStreamerCallback::ChunkNeedsLoad(), ScriptedWorldStreamerCallback::ChunkSize(), SuperSmartPointer< GameServer >::Dispose(), ScriptedWorldStreamerCallback::OnMapChunkCoordinateUpdate(), ScriptedWorldStreamerCallback::OnMapChunkLoad(), ScriptedWorldStreamerCallback::OnMapChunkUnload(), SuperSmartPointer< GameServer >::operator=(), Future::Post(), Future::PostDelayed(), SuperSmartPointer< GameServer >::Replace(), SuperSmartPointer< GameServer >::Reset(), SuperSmartPointerOperationCounter::Shutdown(), SuperSmartPointerOperationCounter::StartUp(), SuperSmartPointer< GameServer >::SuperSmartPointer(), SuperSmartPointerOperationCounter::Update(), and SuperSmartPointer< GameServer >::~SuperSmartPointer().
bool Log::PrintTime
Whether to print time to the console Only change this after InitSubsystems was called