Flaming Torch Framework: Rect Class Reference
Rect Class Reference
#include <Math.hpp>
Public Member Functions
Rect ()
Rect (const Rect &Other)
Rect (f32 Width, f32 Height)
Rect (f32 Left, f32 Right, f32 Top, f32 Bottom)
bool IsInside (const Vector2 &Position) const
bool IsOutside (const Vector2 &Position) const
Rect operator+ (const Rect &Other) const
Rect operator- (const Rect &Other) const
Vector2 Position () const
Vector2 Size () const
Vector2 ToFullSize () const
Public Attributes
f32 Bottom
f32 Left
f32 Right
f32 Top
Constructor & Destructor Documentation
Rect::Rect ()
Referenced by operator+(), and operator-().
Rect::Rect (const Rect & Other)
Rect::Rect (f32 Width, f32 Height)
Rect::Rect (f32 Left, f32 Right, f32 Top, f32 Bottom)
Member Function Documentation
bool Rect::IsInside (const Vector2 & Position) const
bool Rect::IsOutside (const Vector2 & Position) const
Rect Rect::operator+ (const Rect & Other) const inline
References Bottom, Left, Rect(), Right, and Top.
Rect Rect::operator- (const Rect & Other) const inline
References Bottom, Left, Rect(), Right, and Top.
Vector2 Rect::Position () const inline
Vector2 Rect::Size () const inline
Vector2 Rect::ToFullSize () const inline
Member Data Documentation
f32 Rect::Bottom
Referenced by operator+(), and operator-().
f32 Rect::Left
Referenced by operator+(), and operator-().
f32 Rect::Right
Referenced by operator+(), and operator-().
f32 Rect::Top
Referenced by operator+(), and operator-().