Flaming Torch Framework: Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType > Class Template Reference
Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType > Class Template Reference
#include <Delegate.h>
Public Types
typedef Delegate8 type
Public Member Functions
Delegate8 ()
Delegate8 (const Delegate8 &x)
template<class X , class Y >
Delegate8 (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8))
template<class X , class Y >
Delegate8 (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const)
Delegate8 (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8))
template<class X , class Y >
void Bind (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8))
template<class X , class Y >
void Bind (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const)
void Bind (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8))
void clear ()
bool empty () const
const DelegateMemento & GetMemento ()
operator unspecified_bool_type () const
bool operator! () const
bool operator!= (const Delegate8 &x) const
bool operator!= (StaticFunctionPtr funcptr)
RetType operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const
bool operator< (const Delegate8 &x) const
void operator= (const Delegate8 &x)
void operator= (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8))
bool operator== (const Delegate8 &x) const
bool operator== (StaticFunctionPtr funcptr)
bool operator> (const Delegate8 &x) const
void SetMemento (const DelegateMemento &any)
Member Typedef Documentation
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> typedef Delegate8 Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::type
Constructor & Destructor Documentation
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8 () inline
References Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::clear().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8 (const Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8 (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8 (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8 (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) function_to_bind) inline
References Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Bind().
Member Function Documentation
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Bind (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
Referenced by Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator=().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Bind (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> void Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Bind (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindstaticfunc().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> void Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::clear () inline
References Gallant::DelegateMemento::clear().
Referenced by Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> bool Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::empty () const inline
Referenced by Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator unspecified_bool_type().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> const DelegateMemento& Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::GetMemento () inline
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator unspecified_bool_type () const inline
References Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::empty().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> bool Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator! () const inline
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> bool Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator!= (const Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> bool Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator!= (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> RetType Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) const inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureMemPtr(), and Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureThis().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> bool Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator< (const Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> void Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator= (const Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> void Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator= (DesiredRetType(*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) function_to_bind) inline
References Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Bind().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> bool Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator== (const Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> bool Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator== (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> bool Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator> (const Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class RetType = detail::DefaultVoid> void Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::SetMemento (const DelegateMemento & any) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().