Flaming Torch Framework: SuperSmartPointer< type > Class Template Reference
SuperSmartPointer< type > Class Template Reference
#include <SuperSmartPointer.hpp>
Public Member Functions
SuperSmartPointer ()
SuperSmartPointer (type *Object)
SuperSmartPointer (const SuperSmartPointer< type > &o)
~SuperSmartPointer ()
template<typename OutType >
OutType * AsDerived ()
void Dispose ()
const type * Get () const
type * Get ()
int32 ObserverCount ()
operator bool () const
operator bool ()
template<typename OutType >
operator SuperSmartPointer< OutType > ()
operator type * ()
bool operator!= (const SuperSmartPointer< type > &o)
const type & operator* () const
type & operator* ()
const type * operator-> () const
type * operator-> ()
SuperSmartPointer< type > & operator= (const SuperSmartPointer< type > &o)
bool operator== (const SuperSmartPointer< type > &o)
void Replace (type *Object, bool Destroy=true)
void Reset (type *Object)
Friends
template<typename OutType >
class SuperSmartPointer
Detailed Description
template<typename type>
class SuperSmartPointer< type >
Smart Pointer implementation using Observer Pattern and implicit Destruction
Constructor & Destructor Documentation
template<typename type> SuperSmartPointer< type >::SuperSmartPointer () inline
template<typename type> SuperSmartPointer< type >::SuperSmartPointer (type * Object) inline explicit
template<typename type> SuperSmartPointer< type >::SuperSmartPointer (const SuperSmartPointer< type > & o) inline
template<typename type> SuperSmartPointer< type >::~SuperSmartPointer () inline
Member Function Documentation
template<typename type> template<typename OutType > OutType* SuperSmartPointer< type >::AsDerived () inline
returns a Derived object from the base object contained within
template<typename type> void SuperSmartPointer< type >::Dispose () inline
Destroys the contained object
template<typename type> const type* SuperSmartPointer< type >::Get () const inline
Referenced by SuperSmartPointer< GameServer >::AsDerived(), SuperSmartPointer< GameServer >::operator bool(), SuperSmartPointer< WorldChunk >::operator WorldChunk *(), SuperSmartPointer< GameServer >::operator!=(), SuperSmartPointer< GameServer >::operator*(), SuperSmartPointer< GameServer >::operator->(), SuperSmartPointer< GameServer >::operator==(), and ScriptedWorldStreamerCallback::ScriptedWorldStreamerCallback().
template<typename type> type* SuperSmartPointer< type >::Get () inline
template<typename type> int32 SuperSmartPointer< type >::ObserverCount () inline
template<typename type> SuperSmartPointer< type >::operator bool () const inline
template<typename type> SuperSmartPointer< type >::operator bool () inline
template<typename type> template<typename OutType > SuperSmartPointer< type >::operator SuperSmartPointer< OutType > () inline
template<typename type> SuperSmartPointer< type >::operator type * () inline
template<typename type> bool SuperSmartPointer< type >::operator!= (const SuperSmartPointer< type > & o) inline
template<typename type> const type& SuperSmartPointer< type >::operator* () const inline
template<typename type> type& SuperSmartPointer< type >::operator* () inline
template<typename type> const type* SuperSmartPointer< type >::operator-> () const inline
template<typename type> type* SuperSmartPointer< type >::operator-> () inline
template<typename type> SuperSmartPointer<type>& SuperSmartPointer< type >::operator= (const SuperSmartPointer< type > & o) inline
template<typename type> bool SuperSmartPointer< type >::operator== (const SuperSmartPointer< type > & o) inline
template<typename type> void SuperSmartPointer< type >::Replace (type * Object, bool Destroy = true) inline
template<typename type> void SuperSmartPointer< type >::Reset (type * Object) inline
Friends And Related Function Documentation
template<typename type> template<typename OutType > friend class SuperSmartPointer friend