Flaming Torch Framework: SpriteDrawOptions Class Reference
SpriteDrawOptions Class Reference
#include <Sprite.hpp>
Public Member Functions
SpriteDrawOptions ()
SpriteDrawOptions (const SpriteDrawOptions &o)
SpriteDrawOptions & BlendingMode (uint32 Blending)
SpriteDrawOptions & Color (const Vector4 &Color)
SpriteDrawOptions & Colors (const Vector4 &A, const Vector4 &B, const Vector4 &C, const Vector4 &D)
SpriteDrawOptions & Crop (uint32 CropMode, const Rect &CropRect)
SpriteDrawOptions & Flip (bool X, bool Y)
SpriteDrawOptions & NinePatch (bool NinePatch, const Rect &NinePatchRect)
SpriteDrawOptions & NinePatchScale (f32 Scale)
SpriteDrawOptions & Offset (const Vector2 &Offset)
SpriteDrawOptions & Pin (uint32 PinningMode)
SpriteDrawOptions & Position (const Vector2 &Pos)
SpriteDrawOptions & Rotation (f32 Rotation)
SpriteDrawOptions & Scale (const Vector2 &Scale)
SpriteDrawOptions & TextureBorders (const Vector2 &Min, const Vector2 &Max)
SpriteDrawOptions & TexturePosition (const Vector2 &Position)
SpriteDrawOptions & TextureRotation (f32 Rotation)
SpriteDrawOptions & Wireframe (bool Value)
SpriteDrawOptions & WireframePixelSize (f32 Value)
Public Attributes
uint32 BlendingModeValue
Vector4 ColorsValue [4]
Vector4 ColorValue
uint32 CropModeValue
Rect CropRectValue
bool FlipX
bool FlipY
Rect NinePatchRectValue
f32 NinePatchScaleValue
bool NinePatchValue
Vector2 OffsetValue
uint32 PinningModeValue
Vector2 PositionValue
f32 RotationValue
Vector2 ScaleValue
Vector2 TexCoordBorderMax
Vector2 TexCoordBorderMin
Vector2 TexCoordPosition
f32 TexCoordRotation
bool UsingColorsArray
f32 WireframePixelSizeValue
bool WireframeValue
Constructor & Destructor Documentation
SpriteDrawOptions::SpriteDrawOptions () inline
References ColorValue.
SpriteDrawOptions::SpriteDrawOptions (const SpriteDrawOptions & o) inline
References ColorsValue.
Member Function Documentation
SpriteDrawOptions& SpriteDrawOptions::BlendingMode (uint32 Blending) inline
SpriteDrawOptions& SpriteDrawOptions::Color (const Vector4 & Color) inline
SpriteDrawOptions& SpriteDrawOptions::Colors (const Vector4 & A, const Vector4 & B, const Vector4 & C, const Vector4 & D) inline
SpriteDrawOptions& SpriteDrawOptions::Crop (uint32 CropMode, const Rect & CropRect) inline
Crops a texture
Parameters
CropMode one of CropMode::*
CropRect the rectangle to crop with
Note
Ignored on Nine Patches
SpriteDrawOptions& SpriteDrawOptions::Flip (bool X, bool Y) inline
Flips a texture
Parameters
X flip the texture on the X axis
Y flip the texture on the Y axis
SpriteDrawOptions& SpriteDrawOptions::NinePatch (bool NinePatch, const Rect & NinePatchRect) inline
Sets up as a Nine Patch
Parameters
NinePatch whether to use a Nine patch
NinePatchRect the distance between each side of the square for the nine patch
SpriteDrawOptions& SpriteDrawOptions::NinePatchScale (f32 Scale) inline
Sets the Nine Patch Scale
Parameters
Scale the Nine Patch Scale
References Scale().
SpriteDrawOptions& SpriteDrawOptions::Offset (const Vector2 & Offset) inline
References Offset().
Referenced by Offset().
SpriteDrawOptions& SpriteDrawOptions::Pin (uint32 PinningMode) inline
SpriteDrawOptions& SpriteDrawOptions::Position (const Vector2 & Pos) inline
Referenced by TexturePosition().
SpriteDrawOptions& SpriteDrawOptions::Rotation (f32 Rotation) inline
References Rotation().
Referenced by Rotation(), and TextureRotation().
SpriteDrawOptions& SpriteDrawOptions::Scale (const Vector2 & Scale) inline
Scaling specifies the object's size when NinePatching
References Scale().
Referenced by NinePatchScale(), and Scale().
SpriteDrawOptions& SpriteDrawOptions::TextureBorders (const Vector2 & Min, const Vector2 & Max) inline
Set up texture borders
Parameters
Min the min coordinate
Max the maximum coordinate
Note
only works for non-Ninepatch
SpriteDrawOptions& SpriteDrawOptions::TexturePosition (const Vector2 & Position) inline
Sets the texture's position
Parameters
Position is the texture's position
Note
only works for non-Ninepatch
References Position().
SpriteDrawOptions& SpriteDrawOptions::TextureRotation (f32 Rotation) inline
Sets the texture's rotation
Parameters
Rotation rotation in Radians
Note
only works for non-ninepatch
References Rotation().
SpriteDrawOptions& SpriteDrawOptions::Wireframe (bool Value) inline
Sets whether this sprite should be wireframe (lines covering the sprite)
Parameters
Value whether to make this wireframe
Note
Will ignore actual Textures for rendering but will generate the usual geometry
SpriteDrawOptions& SpriteDrawOptions::WireframePixelSize (f32 Value) inline
Sets the wireframe size for this sprite
Parameters
Value the size in pixels of the wireframe line
Note
Will ignore actual Textures for rendering but will generate the usual geometry
Member Data Documentation
uint32 SpriteDrawOptions::BlendingModeValue
Vector4 SpriteDrawOptions::ColorsValue[4]
Referenced by SpriteDrawOptions().
Vector4 SpriteDrawOptions::ColorValue
Referenced by SpriteDrawOptions().
uint32 SpriteDrawOptions::CropModeValue
Rect SpriteDrawOptions::CropRectValue
bool SpriteDrawOptions::FlipX
bool SpriteDrawOptions::FlipY
Rect SpriteDrawOptions::NinePatchRectValue
f32 SpriteDrawOptions::NinePatchScaleValue
bool SpriteDrawOptions::NinePatchValue
Vector2 SpriteDrawOptions::OffsetValue
uint32 SpriteDrawOptions::PinningModeValue
Vector2 SpriteDrawOptions::PositionValue
f32 SpriteDrawOptions::RotationValue
Vector2 SpriteDrawOptions::ScaleValue
Vector2 SpriteDrawOptions::TexCoordBorderMax
Vector2 SpriteDrawOptions::TexCoordBorderMin
Vector2 SpriteDrawOptions::TexCoordPosition
f32 SpriteDrawOptions::TexCoordRotation
bool SpriteDrawOptions::UsingColorsArray
f32 SpriteDrawOptions::WireframePixelSizeValue
bool SpriteDrawOptions::WireframeValue