Flaming Torch Framework: RotateableRect Class Reference
RotateableRect Class Reference
#include <Math.hpp>
Public Member Functions
RotateableRect ()
RotateableRect (const RotateableRect &Other)
RotateableRect (f32 Width, f32 Height, f32 Rotation=0)
RotateableRect (f32 Left, f32 Right, f32 Top, f32 Bottom, f32 Rotation=0)
bool IsInside (const Vector2 &Position) const
bool IsOutside (const Vector2 &Position) const
RotateableRect operator+ (const RotateableRect &Other) const
RotateableRect operator- (const RotateableRect &Other) const
Vector2 Position () const
Vector2 Size () const
Vector2 ToFullSize () const
Public Attributes
f32 Bottom
f32 Left
f32 Right
f32 Rotation
f32 Top
Constructor & Destructor Documentation
RotateableRect::RotateableRect ()
Referenced by operator+(), and operator-().
RotateableRect::RotateableRect (const RotateableRect & Other)
RotateableRect::RotateableRect (f32 Width, f32 Height, f32 Rotation = 0)
RotateableRect::RotateableRect (f32 Left, f32 Right, f32 Top, f32 Bottom, f32 Rotation = 0)
Member Function Documentation
bool RotateableRect::IsInside (const Vector2 & Position) const
bool RotateableRect::IsOutside (const Vector2 & Position) const
RotateableRect RotateableRect::operator+ (const RotateableRect & Other) const inline
References Bottom, Left, Right, RotateableRect(), and Top.
RotateableRect RotateableRect::operator- (const RotateableRect & Other) const inline
References Bottom, Left, Right, RotateableRect(), and Top.
Vector2 RotateableRect::Position () const inline
Vector2 RotateableRect::Size () const inline
Vector2 RotateableRect::ToFullSize () const inline
Member Data Documentation
f32 RotateableRect::Bottom
Referenced by operator+(), and operator-().
f32 RotateableRect::Left
Referenced by operator+(), and operator-().
f32 RotateableRect::Right
Referenced by operator+(), and operator-().
f32 RotateableRect::Rotation
f32 RotateableRect::Top
Referenced by operator+(), and operator-().