Flaming Torch Framework: SuperSmartPointerCollisionManager Class Reference
SuperSmartPointerCollisionManager Class Reference
#include <SuperSmartPointer.hpp>
Public Member Functions
void Add (void *Content, void *Pointer)
void Remove (void *Content)
Public Attributes
std::vector< std::pair< void
*, void * > > RegisteredPointers
Static Public Attributes
static
SuperSmartPointerCollisionManager Instance
Member Function Documentation
void SuperSmartPointerCollisionManager::Add (void * Content, void * Pointer) inline
References Log::Instance, and Log::LogErr().
Referenced by SuperSmartPointer< GameServer >::Replace(), SuperSmartPointer< GameServer >::Reset(), and SuperSmartPointer< GameServer >::SuperSmartPointer().
void SuperSmartPointerCollisionManager::Remove (void * Content) inline
Member Data Documentation
SuperSmartPointerCollisionManager SuperSmartPointerCollisionManager::Instance static
Referenced by SuperSmartPointer< GameServer >::Replace(), SuperSmartPointer< GameServer >::Reset(), and SuperSmartPointer< GameServer >::SuperSmartPointer().
std::vector<std::pair<void *, void *> > SuperSmartPointerCollisionManager::RegisteredPointers