Flaming Torch Framework: ScriptedConsoleCommand Class Reference
ScriptedConsoleCommand Class Reference
#include <Console.hpp>
Inherits ConsoleCommand.
Public Member Functions
ScriptedConsoleCommand ()
void ScriptedMethodProxy (const std::vector< std::string > &Parameters)
Public Member Functions inherited from ConsoleCommand
virtual ~ConsoleCommand ()
Public Attributes
luabind::object ScriptedMethod
Public Attributes inherited from ConsoleCommand
Signal1< const std::vector
< std::string > & > Method
std::string Name
Constructor & Destructor Documentation
ScriptedConsoleCommand::ScriptedConsoleCommand () inline
References Gallant::Signal1< Param1 >::Connect(), ConsoleCommand::Method, and ScriptedMethodProxy().
Member Function Documentation
void ScriptedConsoleCommand::ScriptedMethodProxy (const std::vector< std::string > & Parameters) inline
References GameInterface::Instance, LuaScriptManager::Instance, LuaScriptManager::LogError(), ConsoleCommand::Name, and ScriptedMethod.
Referenced by ScriptedConsoleCommand().
Member Data Documentation
luabind::object ScriptedConsoleCommand::ScriptedMethod
Referenced by ScriptedMethodProxy().