Flaming Torch Framework: Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr > Class Template Reference
Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr > Class Template Reference
#include <Delegate.h>
Inherits Gallant::DelegateMemento.
Public Member Functions
template<class X , class XMemFunc >
void bindconstmemfunc (const X *pthis, XMemFunc function_to_bind)
template<class X , class XMemFunc >
void bindmemfunc (X *pthis, XMemFunc function_to_bind)
template<class DerivedClass , class ParentInvokerSig >
void bindstaticfunc (DerivedClass *pParent, ParentInvokerSig static_function_invoker, StaticFuncPtr function_to_bind)
template<class DerivedClass >
void CopyFrom (DerivedClass *pParent, const DelegateMemento &right)
GenericMemFunc GetClosureMemPtr () const
GenericClass * GetClosureThis () const
UnvoidStaticFuncPtr GetStaticFunction () const
bool IsEqualToStaticFuncPtr (StaticFuncPtr funcptr)
Public Member Functions inherited from Gallant::DelegateMemento
DelegateMemento ()
DelegateMemento (const DelegateMemento &right)
void clear ()
bool empty () const
bool IsEqual (const DelegateMemento &x) const
bool IsLess (const DelegateMemento &right) const
bool operator! () const
bool operator< (const DelegateMemento &right)
DelegateMemento & operator= (const DelegateMemento &right)
bool operator> (const DelegateMemento &right)
Additional Inherited Members
Protected Types inherited from Gallant::DelegateMemento
typedef void(detail::GenericClass::* GenericMemFuncType)()
Protected Member Functions inherited from Gallant::DelegateMemento
void SetMementoFrom (const DelegateMemento &right)
Protected Attributes inherited from Gallant::DelegateMemento
GenericMemFuncType m_pFunction
detail::GenericClass * m_pthis
Member Function Documentation
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> template<class X , class XMemFunc > void Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc (const X * pthis, XMemFunc function_to_bind) inline
Referenced by Gallant::Delegate0< RetType >::Bind(), Gallant::Delegate1< Param1, RetType >::Bind(), Gallant::Delegate2< Param1, Param2, RetType >::Bind(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::Bind(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Bind(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::Bind(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Bind(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::Bind(), Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Bind(), Gallant::Delegate0< RetType >::Delegate0(), Gallant::Delegate1< Param1, RetType >::Delegate1(), Gallant::Delegate2< Param1, Param2, RetType >::Delegate2(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::Delegate5(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::Delegate7(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> template<class X , class XMemFunc > void Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc (X * pthis, XMemFunc function_to_bind) inline
Referenced by Gallant::Delegate0< RetType >::Bind(), Gallant::Delegate1< Param1, RetType >::Bind(), Gallant::Delegate2< Param1, Param2, RetType >::Bind(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::Bind(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Bind(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::Bind(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Bind(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::Bind(), Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Bind(), Gallant::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::bindstaticfunc(), Gallant::Delegate0< RetType >::Delegate0(), Gallant::Delegate1< Param1, RetType >::Delegate1(), Gallant::Delegate2< Param1, Param2, RetType >::Delegate2(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::Delegate5(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::Delegate7(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> template<class DerivedClass , class ParentInvokerSig > void Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindstaticfunc (DerivedClass * pParent, ParentInvokerSig static_function_invoker, StaticFuncPtr function_to_bind) inline
Referenced by Gallant::Delegate0< RetType >::Bind(), Gallant::Delegate1< Param1, RetType >::Bind(), Gallant::Delegate2< Param1, Param2, RetType >::Bind(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::Bind(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Bind(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::Bind(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Bind(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::Bind(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Bind().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> template<class DerivedClass > void Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom (DerivedClass * pParent, const DelegateMemento & right) inline
Referenced by Gallant::Delegate0< RetType >::Delegate0(), Gallant::Delegate1< Param1, RetType >::Delegate1(), Gallant::Delegate2< Param1, Param2, RetType >::Delegate2(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::Delegate3(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::Delegate4(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::Delegate5(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::Delegate6(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::Delegate7(), Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::Delegate8(), Gallant::Delegate0< RetType >::operator=(), Gallant::Delegate1< Param1, RetType >::operator=(), Gallant::Delegate2< Param1, Param2, RetType >::operator=(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator=(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator=(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator=(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator=(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator=(), Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator=(), Gallant::Delegate0< RetType >::SetMemento(), Gallant::Delegate1< Param1, RetType >::SetMemento(), Gallant::Delegate2< Param1, Param2, RetType >::SetMemento(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::SetMemento(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::SetMemento(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::SetMemento(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::SetMemento(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::SetMemento(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::SetMemento().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> GenericMemFunc Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureMemPtr () const inline
Referenced by Gallant::Delegate0< RetType >::operator()(), Gallant::Delegate1< Param1, RetType >::operator()(), Gallant::Delegate2< Param1, Param2, RetType >::operator()(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator()(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator()(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator()(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator()(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator()(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator()().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> GenericClass* Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureThis () const inline
Referenced by Gallant::Delegate0< RetType >::operator()(), Gallant::Delegate1< Param1, RetType >::operator()(), Gallant::Delegate2< Param1, Param2, RetType >::operator()(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator()(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator()(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator()(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator()(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator()(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator()().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> UnvoidStaticFuncPtr Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetStaticFunction () const inline
Referenced by Gallant::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::IsEqualToStaticFuncPtr().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> bool Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr (StaticFuncPtr funcptr) inline
Referenced by Gallant::Delegate0< RetType >::operator!=(), Gallant::Delegate1< Param1, RetType >::operator!=(), Gallant::Delegate2< Param1, Param2, RetType >::operator!=(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator!=(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator!=(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator!=(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator!=(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator!=(), Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator!=(), Gallant::Delegate0< RetType >::operator==(), Gallant::Delegate1< Param1, RetType >::operator==(), Gallant::Delegate2< Param1, Param2, RetType >::operator==(), Gallant::Delegate3< Param1, Param2, Param3, RetType >::operator==(), Gallant::Delegate4< Param1, Param2, Param3, Param4, RetType >::operator==(), Gallant::Delegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator==(), Gallant::Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator==(), Gallant::Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator==(), and Gallant::Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator==().