Flaming Torch Framework: Gallant::Delegate0< RetType > Class Template Reference
Gallant::Delegate0< RetType > Class Template Reference
#include <Delegate.h>
Public Types
typedef Delegate0 type
Public Member Functions
Delegate0 ()
Delegate0 (const Delegate0 &x)
template<class X , class Y >
Delegate0 (Y *pthis, DesiredRetType(X::*function_to_bind)())
template<class X , class Y >
Delegate0 (const Y *pthis, DesiredRetType(X::*function_to_bind)() const)
Delegate0 (DesiredRetType(*function_to_bind)())
template<class X , class Y >
void Bind (Y *pthis, DesiredRetType(X::*function_to_bind)())
template<class X , class Y >
void Bind (const Y *pthis, DesiredRetType(X::*function_to_bind)() const)
void Bind (DesiredRetType(*function_to_bind)())
void clear ()
bool empty () const
const DelegateMemento & GetMemento ()
operator unspecified_bool_type () const
bool operator! () const
bool operator!= (const Delegate0 &x) const
bool operator!= (StaticFunctionPtr funcptr)
RetType operator() () const
bool operator< (const Delegate0 &x) const
void operator= (const Delegate0 &x)
void operator= (DesiredRetType(*function_to_bind)())
bool operator== (const Delegate0 &x) const
bool operator== (StaticFunctionPtr funcptr)
bool operator> (const Delegate0 &x) const
void SetMemento (const DelegateMemento &any)
Member Typedef Documentation
template<class RetType = detail::DefaultVoid> typedef Delegate0 Gallant::Delegate0< RetType >::type
Constructor & Destructor Documentation
template<class RetType = detail::DefaultVoid> Gallant::Delegate0< RetType >::Delegate0 () inline
References Gallant::Delegate0< RetType >::clear().
template<class RetType = detail::DefaultVoid> Gallant::Delegate0< RetType >::Delegate0 (const Delegate0< RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate0< RetType >::Delegate0 (Y * pthis, DesiredRetType(X::*)() function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
template<class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate0< RetType >::Delegate0 (const Y * pthis, DesiredRetType(X::*)() const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class RetType = detail::DefaultVoid> Gallant::Delegate0< RetType >::Delegate0 (DesiredRetType(*)() function_to_bind) inline
References Gallant::Delegate0< RetType >::Bind().
Member Function Documentation
template<class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate0< RetType >::Bind (Y * pthis, DesiredRetType(X::*)() function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
Referenced by Gallant::Delegate0< RetType >::Delegate0(), and Gallant::Delegate0< RetType >::operator=().
template<class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate0< RetType >::Bind (const Y * pthis, DesiredRetType(X::*)() const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class RetType = detail::DefaultVoid> void Gallant::Delegate0< RetType >::Bind (DesiredRetType(*)() function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindstaticfunc().
template<class RetType = detail::DefaultVoid> void Gallant::Delegate0< RetType >::clear () inline
References Gallant::DelegateMemento::clear().
Referenced by Gallant::Delegate0< RetType >::Delegate0().
template<class RetType = detail::DefaultVoid> bool Gallant::Delegate0< RetType >::empty () const inline
Referenced by Gallant::Delegate0< RetType >::operator unspecified_bool_type().
template<class RetType = detail::DefaultVoid> const DelegateMemento& Gallant::Delegate0< RetType >::GetMemento () inline
template<class RetType = detail::DefaultVoid> Gallant::Delegate0< RetType >::operator unspecified_bool_type () const inline
References Gallant::Delegate0< RetType >::empty().
template<class RetType = detail::DefaultVoid> bool Gallant::Delegate0< RetType >::operator! () const inline
template<class RetType = detail::DefaultVoid> bool Gallant::Delegate0< RetType >::operator!= (const Delegate0< RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class RetType = detail::DefaultVoid> bool Gallant::Delegate0< RetType >::operator!= (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class RetType = detail::DefaultVoid> RetType Gallant::Delegate0< RetType >::operator() () const inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureMemPtr(), and Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureThis().
template<class RetType = detail::DefaultVoid> bool Gallant::Delegate0< RetType >::operator< (const Delegate0< RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class RetType = detail::DefaultVoid> void Gallant::Delegate0< RetType >::operator= (const Delegate0< RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class RetType = detail::DefaultVoid> void Gallant::Delegate0< RetType >::operator= (DesiredRetType(*)() function_to_bind) inline
References Gallant::Delegate0< RetType >::Bind().
template<class RetType = detail::DefaultVoid> bool Gallant::Delegate0< RetType >::operator== (const Delegate0< RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class RetType = detail::DefaultVoid> bool Gallant::Delegate0< RetType >::operator== (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class RetType = detail::DefaultVoid> bool Gallant::Delegate0< RetType >::operator> (const Delegate0< RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class RetType = detail::DefaultVoid> void Gallant::Delegate0< RetType >::SetMemento (const DelegateMemento & any) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().