Flaming Torch Framework: Gallant::Delegate2< Param1, Param2, RetType > Class Template Reference
Gallant::Delegate2< Param1, Param2, RetType > Class Template Reference
#include <Delegate.h>
Public Types
typedef Delegate2 type
Public Member Functions
Delegate2 ()
Delegate2 (const Delegate2 &x)
template<class X , class Y >
Delegate2 (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2))
template<class X , class Y >
Delegate2 (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2) const)
Delegate2 (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2))
template<class X , class Y >
void Bind (Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2))
template<class X , class Y >
void Bind (const Y *pthis, DesiredRetType(X::*function_to_bind)(Param1 p1, Param2 p2) const)
void Bind (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2))
void clear ()
bool empty () const
const DelegateMemento & GetMemento ()
operator unspecified_bool_type () const
bool operator! () const
bool operator!= (const Delegate2 &x) const
bool operator!= (StaticFunctionPtr funcptr)
RetType operator() (Param1 p1, Param2 p2) const
bool operator< (const Delegate2 &x) const
void operator= (const Delegate2 &x)
void operator= (DesiredRetType(*function_to_bind)(Param1 p1, Param2 p2))
bool operator== (const Delegate2 &x) const
bool operator== (StaticFunctionPtr funcptr)
bool operator> (const Delegate2 &x) const
void SetMemento (const DelegateMemento &any)
Member Typedef Documentation
template<class Param1, class Param2, class RetType = detail::DefaultVoid> typedef Delegate2 Gallant::Delegate2< Param1, Param2, RetType >::type
Constructor & Destructor Documentation
template<class Param1, class Param2, class RetType = detail::DefaultVoid> Gallant::Delegate2< Param1, Param2, RetType >::Delegate2 () inline
References Gallant::Delegate2< Param1, Param2, RetType >::clear().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> Gallant::Delegate2< Param1, Param2, RetType >::Delegate2 (const Delegate2< Param1, Param2, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate2< Param1, Param2, RetType >::Delegate2 (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> template<class X , class Y > Gallant::Delegate2< Param1, Param2, RetType >::Delegate2 (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> Gallant::Delegate2< Param1, Param2, RetType >::Delegate2 (DesiredRetType(*)(Param1 p1, Param2 p2) function_to_bind) inline
References Gallant::Delegate2< Param1, Param2, RetType >::Bind().
Member Function Documentation
template<class Param1, class Param2, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate2< Param1, Param2, RetType >::Bind (Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc().
Referenced by Gallant::Delegate2< Param1, Param2, RetType >::Delegate2(), and Gallant::Delegate2< Param1, Param2, RetType >::operator=().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> template<class X , class Y > void Gallant::Delegate2< Param1, Param2, RetType >::Bind (const Y * pthis, DesiredRetType(X::*)(Param1 p1, Param2 p2) const function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> void Gallant::Delegate2< Param1, Param2, RetType >::Bind (DesiredRetType(*)(Param1 p1, Param2 p2) function_to_bind) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindstaticfunc().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> void Gallant::Delegate2< Param1, Param2, RetType >::clear () inline
References Gallant::DelegateMemento::clear().
Referenced by Gallant::Delegate2< Param1, Param2, RetType >::Delegate2().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> bool Gallant::Delegate2< Param1, Param2, RetType >::empty () const inline
Referenced by Gallant::Delegate2< Param1, Param2, RetType >::operator unspecified_bool_type().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> const DelegateMemento& Gallant::Delegate2< Param1, Param2, RetType >::GetMemento () inline
template<class Param1, class Param2, class RetType = detail::DefaultVoid> Gallant::Delegate2< Param1, Param2, RetType >::operator unspecified_bool_type () const inline
References Gallant::Delegate2< Param1, Param2, RetType >::empty().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> bool Gallant::Delegate2< Param1, Param2, RetType >::operator! () const inline
template<class Param1, class Param2, class RetType = detail::DefaultVoid> bool Gallant::Delegate2< Param1, Param2, RetType >::operator!= (const Delegate2< Param1, Param2, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> bool Gallant::Delegate2< Param1, Param2, RetType >::operator!= (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> RetType Gallant::Delegate2< Param1, Param2, RetType >::operator() (Param1 p1, Param2 p2) const inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureMemPtr(), and Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureThis().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> bool Gallant::Delegate2< Param1, Param2, RetType >::operator< (const Delegate2< Param1, Param2, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> void Gallant::Delegate2< Param1, Param2, RetType >::operator= (const Delegate2< Param1, Param2, RetType > & x) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> void Gallant::Delegate2< Param1, Param2, RetType >::operator= (DesiredRetType(*)(Param1 p1, Param2 p2) function_to_bind) inline
References Gallant::Delegate2< Param1, Param2, RetType >::Bind().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> bool Gallant::Delegate2< Param1, Param2, RetType >::operator== (const Delegate2< Param1, Param2, RetType > & x) const inline
References Gallant::DelegateMemento::IsEqual().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> bool Gallant::Delegate2< Param1, Param2, RetType >::operator== (StaticFunctionPtr funcptr) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> bool Gallant::Delegate2< Param1, Param2, RetType >::operator> (const Delegate2< Param1, Param2, RetType > & x) const inline
References Gallant::DelegateMemento::IsLess().
template<class Param1, class Param2, class RetType = detail::DefaultVoid> void Gallant::Delegate2< Param1, Param2, RetType >::SetMemento (const DelegateMemento & any) inline
References Gallant::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom().