Flaming Torch Framework: Gallant::Signal4< Param1, Param2, Param3, Param4 > Class Template Reference
Gallant::Signal4< Param1, Param2, Param3, Param4 > Class Template Reference
#include <Signal.h>
Public Types
typedef Delegate4< Param1,
Param2, Param3, Param4 > _Delegate
Public Member Functions
void Connect (_Delegate delegate)
template<class X , class Y >
void Connect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4))
template<class X , class Y >
void Connect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) const)
void Disconnect (_Delegate delegate)
template<class X , class Y >
void Disconnect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4))
template<class X , class Y >
void Disconnect (Y *obj, void(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) const)
void Emit (Param1 p1, Param2 p2, Param3 p3, Param4 p4) const
void operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4) const
Member Typedef Documentation
template<class Param1 , class Param2 , class Param3 , class Param4 > typedef Delegate4< Param1, Param2, Param3, Param4 > Gallant::Signal4< Param1, Param2, Param3, Param4 >::_Delegate
Member Function Documentation
template<class Param1 , class Param2 , class Param3 , class Param4 > void Gallant::Signal4< Param1, Param2, Param3, Param4 >::Connect (_Delegate delegate) inline
template<class Param1 , class Param2 , class Param3 , class Param4 > template<class X , class Y > void Gallant::Signal4< Param1, Param2, Param3, Param4 >::Connect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 > template<class X , class Y > void Gallant::Signal4< Param1, Param2, Param3, Param4 >::Connect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) const func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 > void Gallant::Signal4< Param1, Param2, Param3, Param4 >::Disconnect (_Delegate delegate) inline
template<class Param1 , class Param2 , class Param3 , class Param4 > template<class X , class Y > void Gallant::Signal4< Param1, Param2, Param3, Param4 >::Disconnect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 > template<class X , class Y > void Gallant::Signal4< Param1, Param2, Param3, Param4 >::Disconnect (Y * obj, void(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) const func) inline
References Gallant::MakeDelegate().
template<class Param1 , class Param2 , class Param3 , class Param4 > void Gallant::Signal4< Param1, Param2, Param3, Param4 >::Emit (Param1 p1, Param2 p2, Param3 p3, Param4 p4) const inline
Referenced by Gallant::Signal4< Param1, Param2, Param3, Param4 >::operator()().
template<class Param1 , class Param2 , class Param3 , class Param4 > void Gallant::Signal4< Param1, Param2, Param3, Param4 >::operator() (Param1 p1, Param2 p2, Param3 p3, Param4 p4) const inline
References Gallant::Signal4< Param1, Param2, Param3, Param4 >::Emit().