Flaming Torch Framework: InputCenter::ScriptedContext Class Reference
InputCenter::ScriptedContext Class Reference
#include <Input.hpp>
Inherits InputCenter::Context.
Public Member Functions
ScriptedContext ()
ScriptedContext (const std::string &_Name)
void OnAction (const Action &TheAction)
void OnCharacterEntered (wchar_t Character)
void OnGainFocus ()
bool OnJoystickAxis (const JoystickAxisInfo &Axis)
bool OnJoystickButton (const JoystickButtonInfo &Button)
void OnJoystickConnected (uint8 Index)
void OnJoystickDisconnected (uint8 Index)
bool OnKey (const KeyInfo &Key)
void OnLoseFocus ()
bool OnMouseButton (const MouseButtonInfo &Button)
void OnMouseMove (const Vector3 &Position)
Public Member Functions inherited from InputCenter::Context
virtual ~Context ()
Public Attributes
luabind::object OnActionFunction
luabind::object OnCharacterEnteredFunction
luabind::object OnGainFocusFunction
luabind::object OnJoystickAxisFunction
luabind::object OnJoystickButtonFunction
luabind::object OnJoystickConnectedFunction
luabind::object OnJoystickDisconnectedFunction
luabind::object OnKeyFunction
luabind::object OnLoseFocusFunction
luabind::object OnMouseButtonFunction
luabind::object OnMouseMoveFunction
Public Attributes inherited from InputCenter::Context
std::string Name
Constructor & Destructor Documentation
InputCenter::ScriptedContext::ScriptedContext () inline
InputCenter::ScriptedContext::ScriptedContext (const std::string & _Name) inline
References InputCenter::Context::Name.
Member Function Documentation
void InputCenter::ScriptedContext::OnAction (const Action & TheAction) inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnActionFunction.
void InputCenter::ScriptedContext::OnCharacterEntered (wchar_t Character) inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnCharacterEnteredFunction.
void InputCenter::ScriptedContext::OnGainFocus () inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnGainFocusFunction.
bool InputCenter::ScriptedContext::OnJoystickAxis (const JoystickAxisInfo & Axis) inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnJoystickAxisFunction.
bool InputCenter::ScriptedContext::OnJoystickButton (const JoystickButtonInfo & Button) inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnJoystickButtonFunction.
void InputCenter::ScriptedContext::OnJoystickConnected (uint8 Index) inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnJoystickConnectedFunction.
void InputCenter::ScriptedContext::OnJoystickDisconnected (uint8 Index) inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnJoystickDisconnectedFunction.
bool InputCenter::ScriptedContext::OnKey (const KeyInfo & Key) inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnKeyFunction.
void InputCenter::ScriptedContext::OnLoseFocus () inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnLoseFocusFunction.
bool InputCenter::ScriptedContext::OnMouseButton (const MouseButtonInfo & Button) inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnMouseButtonFunction.
void InputCenter::ScriptedContext::OnMouseMove (const Vector3 & Position) inline virtual
Implements InputCenter::Context.
References LuaScriptManager::Instance, LuaScriptManager::LogError(), InputCenter::Context::Name, and OnMouseMoveFunction.
Member Data Documentation
luabind::object InputCenter::ScriptedContext::OnActionFunction
Referenced by OnAction().
luabind::object InputCenter::ScriptedContext::OnCharacterEnteredFunction
Referenced by OnCharacterEntered().
luabind::object InputCenter::ScriptedContext::OnGainFocusFunction
Referenced by OnGainFocus().
luabind::object InputCenter::ScriptedContext::OnJoystickAxisFunction
Referenced by OnJoystickAxis().
luabind::object InputCenter::ScriptedContext::OnJoystickButtonFunction
Referenced by OnJoystickButton().
luabind::object InputCenter::ScriptedContext::OnJoystickConnectedFunction
Referenced by OnJoystickConnected().
luabind::object InputCenter::ScriptedContext::OnJoystickDisconnectedFunction
Referenced by OnJoystickDisconnected().
luabind::object InputCenter::ScriptedContext::OnKeyFunction
Referenced by OnKey().
luabind::object InputCenter::ScriptedContext::OnLoseFocusFunction
Referenced by OnLoseFocus().
luabind::object InputCenter::ScriptedContext::OnMouseButtonFunction
Referenced by OnMouseButton().
luabind::object InputCenter::ScriptedContext::OnMouseMoveFunction
Referenced by OnMouseMove().