var hierarchy =
[
    [ "FlamingTorch::AxisAlignedBoundingBox", "class_flaming_torch_1_1_axis_aligned_bounding_box.html", null ],
    [ "FlamingTorch::BaseScriptableInstance", "class_flaming_torch_1_1_base_scriptable_instance.html", [
      [ "FlamingTorch::UIManager", "class_flaming_torch_1_1_u_i_manager.html", null ]
    ] ],
    [ "FlamingTorch::BoundingSphere", "class_flaming_torch_1_1_bounding_sphere.html", null ],
    [ "FlamingTorch::Camera", "class_flaming_torch_1_1_camera.html", null ],
    [ "FlamingTorch::ConsoleCommand", "class_flaming_torch_1_1_console_command.html", null ],
    [ "FlamingTorch::ConsoleVariable", "struct_flaming_torch_1_1_console_variable.html", null ],
    [ "FlamingTorch::CRC32", "class_flaming_torch_1_1_c_r_c32.html", null ],
    [ "FlamingTorch::DisposableResource< type >", "class_flaming_torch_1_1_disposable_resource.html", null ],
    [ "FlamingTorch::DynamicLibrary", "class_flaming_torch_1_1_dynamic_library.html", null ],
    [ "FlamingTorch::FileSystemUtils", "class_flaming_torch_1_1_file_system_utils.html", null ],
    [ "FlamingTorch::Font", "class_flaming_torch_1_1_font.html", null ],
    [ "FlamingTorch::GenericConfig", "class_flaming_torch_1_1_generic_config.html", null ],
    [ "FlamingTorch::GenericConfig::Section", "class_flaming_torch_1_1_generic_config.html#class_flaming_torch_1_1_generic_config_1_1_section", null ],
    [ "FlamingTorch::GenericConfig::Value", "class_flaming_torch_1_1_generic_config_1_1_value.html", [
      [ "FlamingTorch::GenericConfig::FloatValue", "class_flaming_torch_1_1_generic_config_1_1_float_value.html", null ],
      [ "FlamingTorch::GenericConfig::IntValue", "class_flaming_torch_1_1_generic_config_1_1_int_value.html", null ]
    ] ],
    [ "FlamingTorch::Glyph", "class_flaming_torch_1_1_glyph.html", null ],
    [ "FlamingTorch::Input::Action", "class_flaming_torch_1_1_input_1_1_action.html", null ],
    [ "FlamingTorch::Input::Context", "class_flaming_torch_1_1_input_1_1_context.html", null ],
    [ "FlamingTorch::Input::JoystickAxisInfo", "class_flaming_torch_1_1_input_1_1_joystick_axis_info.html", null ],
    [ "FlamingTorch::Input::JoystickButtonInfo", "class_flaming_torch_1_1_input_1_1_joystick_button_info.html", null ],
    [ "FlamingTorch::Input::KeyInfo", "class_flaming_torch_1_1_input_1_1_key_info.html", null ],
    [ "FlamingTorch::Input::MouseButtonInfo", "class_flaming_torch_1_1_input_1_1_mouse_button_info.html", null ],
    [ "FlamingTorch::Input::TouchInfo", "class_flaming_torch_1_1_input_1_1_touch_info.html", null ],
    [ "FlamingTorch::IRendererImplementation", "class_flaming_torch_1_1_i_renderer_implementation.html", [
      [ "FlamingTorch::NULLRendererImplementation", "class_flaming_torch_1_1_n_u_l_l_renderer_implementation.html", null ]
    ] ],
    [ "FlamingTorch::ISoundManagerImplementation", "class_flaming_torch_1_1_i_sound_manager_implementation.html", [
      [ "FlamingTorch::NULLSoundManagerImplementation", "class_flaming_torch_1_1_n_u_l_l_sound_manager_implementation.html", null ]
    ] ],
    [ "FlamingTorch::LinearTimer", "class_flaming_torch_1_1_linear_timer.html", null ],
    [ "FlamingTorch::LuaEventGroup", "class_flaming_torch_1_1_lua_event_group.html", null ],
    [ "FlamingTorch::LuaGlobalsTracker", "class_flaming_torch_1_1_lua_globals_tracker.html", null ],
    [ "FlamingTorch::LuaLib", "class_flaming_torch_1_1_lua_lib.html", [
      [ "FlamingTorch::FrameworkLib", "class_flaming_torch_1_1_framework_lib.html", null ],
      [ "FlamingTorch::GameInterface", "class_flaming_torch_1_1_game_interface.html", [
        [ "FlamingTorch::NativeGameInterface", "class_flaming_torch_1_1_native_game_interface.html", null ]
      ] ]
    ] ],
    [ "FlamingTorch::LuaScript", "class_flaming_torch_1_1_lua_script.html", null ],
    [ "FlamingTorch::MathUtils", "class_flaming_torch_1_1_math_utils.html", null ],
    [ "FlamingTorch::Matrix4x4", "class_flaming_torch_1_1_matrix4x4.html", null ],
    [ "FlamingTorch::PackageFileSystemManager::Package", "class_flaming_torch_1_1_package_file_system_manager_1_1_package.html", null ],
    [ "FlamingTorch::PackageFileSystemManager::Package::FileEntry", "class_flaming_torch_1_1_package_file_system_manager_1_1_package.html#class_flaming_torch_1_1_package_file_system_manager_1_1_package_1_1_file_entry", null ],
    [ "FlamingTorch::Path", "class_flaming_torch_1_1_path.html", null ],
    [ "FlamingTorch::Plane", "class_flaming_torch_1_1_plane.html", null ],
    [ "FlamingTorch::PosCol", "namespace_flaming_torch.html#struct_flaming_torch_1_1_pos_col", null ],
    [ "FlamingTorch::PosTexCol", "namespace_flaming_torch.html#struct_flaming_torch_1_1_pos_tex_col", null ],
    [ "FlamingTorch::Profiler::Packet", "class_flaming_torch_1_1_profiler.html#struct_flaming_torch_1_1_profiler_1_1_packet", null ],
    [ "FlamingTorch::ProfilerFragment", "class_flaming_torch_1_1_profiler_fragment.html", null ],
    [ "FlamingTorch::Quaternion", "class_flaming_torch_1_1_quaternion.html", null ],
    [ "FlamingTorch::Randomizer", "class_flaming_torch_1_1_randomizer.html", null ],
    [ "FlamingTorch::Ray", "class_flaming_torch_1_1_ray.html", null ],
    [ "FlamingTorch::Rect", "class_flaming_torch_1_1_rect.html", null ],
    [ "FlamingTorch::RenderCreateOptions", "struct_flaming_torch_1_1_render_create_options.html", null ],
    [ "FlamingTorch::RendererCapabilities", "class_flaming_torch_1_1_renderer_capabilities.html", null ],
    [ "FlamingTorch::RendererDisplayMode", "namespace_flaming_torch.html#class_flaming_torch_1_1_renderer_display_mode", null ],
    [ "FlamingTorch::RendererEvent", "class_flaming_torch_1_1_renderer_event.html", null ],
    [ "FlamingTorch::RendererFrameStats", "class_flaming_torch_1_1_renderer_frame_stats.html", null ],
    [ "FlamingTorch::RenderTextUtils", "class_flaming_torch_1_1_render_text_utils.html", null ],
    [ "FlamingTorch::RotateableRect", "class_flaming_torch_1_1_rotateable_rect.html", null ],
    [ "FlamingTorch::SoundManager::Music", "class_flaming_torch_1_1_sound_manager_1_1_music.html", null ],
    [ "FlamingTorch::SoundManager::Sound", "class_flaming_torch_1_1_sound_manager_1_1_sound.html", null ],
    [ "FlamingTorch::Sprite", "class_flaming_torch_1_1_sprite.html", null ],
    [ "FlamingTorch::SpriteDrawOptions", "class_flaming_torch_1_1_sprite_draw_options.html", null ],
    [ "FlamingTorch::Stream", "class_flaming_torch_1_1_stream.html", [
      [ "FlamingTorch::ConstantMemoryStream", "class_flaming_torch_1_1_constant_memory_stream.html", null ],
      [ "FlamingTorch::FileStream", "class_flaming_torch_1_1_file_stream.html", null ],
      [ "FlamingTorch::MemoryStream", "class_flaming_torch_1_1_memory_stream.html", null ],
      [ "FlamingTorch::PackageFileSystemManager::PackageStream", "class_flaming_torch_1_1_package_file_system_manager_1_1_package_stream.html", null ]
    ] ],
    [ "FlamingTorch::StreamProcessor", "class_flaming_torch_1_1_stream_processor.html", [
      [ "FlamingTorch::XORStreamProcessor", "class_flaming_torch_1_1_x_o_r_stream_processor.html", null ]
    ] ],
    [ "FlamingTorch::StringUtils", "class_flaming_torch_1_1_string_utils.html", null ],
    [ "FlamingTorch::SubSystem", "class_flaming_torch_1_1_sub_system.html", [
      [ "FlamingTorch::Console", "class_flaming_torch_1_1_console.html", null ],
      [ "FlamingTorch::FileSystemWatcher", "class_flaming_torch_1_1_file_system_watcher.html", null ],
      [ "FlamingTorch::FPSCounter", "class_flaming_torch_1_1_f_p_s_counter.html", null ],
      [ "FlamingTorch::Future", "class_flaming_torch_1_1_future.html", null ],
      [ "FlamingTorch::GameClock", "class_flaming_torch_1_1_game_clock.html", null ],
      [ "FlamingTorch::Input", "class_flaming_torch_1_1_input.html", null ],
      [ "FlamingTorch::Log", "class_flaming_torch_1_1_log.html", null ],
      [ "FlamingTorch::LuaScriptManager", "class_flaming_torch_1_1_lua_script_manager.html", null ],
      [ "FlamingTorch::PackageFileSystemManager", "class_flaming_torch_1_1_package_file_system_manager.html", null ],
      [ "FlamingTorch::Profiler", "class_flaming_torch_1_1_profiler.html", null ],
      [ "FlamingTorch::Renderer", "class_flaming_torch_1_1_renderer.html", null ],
      [ "FlamingTorch::ResourceManager", "class_flaming_torch_1_1_resource_manager.html", null ],
      [ "FlamingTorch::SoundManager", "class_flaming_torch_1_1_sound_manager.html", null ]
    ] ],
    [ "FlamingTorch::TextParams", "class_flaming_torch_1_1_text_params.html", null ],
    [ "FlamingTorch::TextRenderer", "class_flaming_torch_1_1_text_renderer.html", null ],
    [ "FlamingTorch::Texture", "class_flaming_torch_1_1_texture.html", null ],
    [ "FlamingTorch::TextureBuffer", "class_flaming_torch_1_1_texture_buffer.html", null ],
    [ "FlamingTorch::TextureEncoderInfo", "struct_flaming_torch_1_1_texture_encoder_info.html", null ],
    [ "FlamingTorch::TextureGroup", "class_flaming_torch_1_1_texture_group.html", null ],
    [ "FlamingTorch::TexturePacker", "class_flaming_torch_1_1_texture_packer.html", null ],
    [ "FlamingTorch::TexturePacker::SortedTexture", "class_flaming_torch_1_1_texture_packer_1_1_sorted_texture.html", null ],
    [ "FlamingTorch::TexturePackerIndex", "class_flaming_torch_1_1_texture_packer_index.html", null ],
    [ "FlamingTorch::TiledMap", "class_flaming_torch_1_1_tiled_map.html", null ],
    [ "FlamingTorch::TiledMap::Layer", "class_flaming_torch_1_1_tiled_map.html#class_flaming_torch_1_1_tiled_map_1_1_layer", null ],
    [ "FlamingTorch::TiledMap::Layer::TileInfo", "class_flaming_torch_1_1_tiled_map.html#struct_flaming_torch_1_1_tiled_map_1_1_layer_1_1_tile_info", null ],
    [ "FlamingTorch::TiledMap::MapObject", "class_flaming_torch_1_1_tiled_map.html#class_flaming_torch_1_1_tiled_map_1_1_map_object", null ],
    [ "FlamingTorch::TiledMap::UniqueTilesetInfo", "class_flaming_torch_1_1_tiled_map.html#class_flaming_torch_1_1_tiled_map_1_1_unique_tileset_info", null ],
    [ "FlamingTorch::TiledMapInitOptions", "class_flaming_torch_1_1_tiled_map_init_options.html", null ],
    [ "FlamingTorch::UIElement", "class_flaming_torch_1_1_u_i_element.html", [
      [ "FlamingTorch::UIGroup", "class_flaming_torch_1_1_u_i_group.html", null ],
      [ "FlamingTorch::UIHorizontalGroup", "class_flaming_torch_1_1_u_i_horizontal_group.html", null ],
      [ "FlamingTorch::UISprite", "class_flaming_torch_1_1_u_i_sprite.html", [
        [ "FlamingTorch::UIButton", "class_flaming_torch_1_1_u_i_button.html", null ]
      ] ],
      [ "FlamingTorch::UIText", "class_flaming_torch_1_1_u_i_text.html", null ],
      [ "FlamingTorch::UIVerticalGroup", "class_flaming_torch_1_1_u_i_vertical_group.html", null ]
    ] ],
    [ "FlamingTorch::UILayout", "class_flaming_torch_1_1_u_i_layout.html", null ],
    [ "FlamingTorch::UIText::StringInfo", "class_flaming_torch_1_1_u_i_text.html#struct_flaming_torch_1_1_u_i_text_1_1_string_info", null ],
    [ "FlamingTorch::Vector2", "class_flaming_torch_1_1_vector2.html", null ],
    [ "FlamingTorch::Vector3", "class_flaming_torch_1_1_vector3.html", null ],
    [ "FlamingTorch::Vector4", "class_flaming_torch_1_1_vector4.html", null ],
    [ "FlamingTorch::VertexElementDescriptor", "namespace_flaming_torch.html#struct_flaming_torch_1_1_vertex_element_descriptor", null ],
    [ "shared_ptr", null, [
      [ "FlamingTorch::DisposablePointer< Context >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< ElementInfo >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::ConsoleCommand >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::FileStream >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::Font >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::GenericConfig >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::ISoundManagerImplementation >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::LuaScript >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::SoundManager::Music >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::Stream >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::StreamProcessor >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::Texture >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::TextureBuffer >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::TextureGroup >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::TexturePacker >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::TiledMap::Layer >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::UIElement >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FlamingTorch::UIManager >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< Font >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< FutureInfo >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< Music >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< Package >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< Sound >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< Texture >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< TexturePacker >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< UIElement >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< UILayout >", "class_flaming_torch_1_1_disposable_pointer.html", null ],
      [ "FlamingTorch::DisposablePointer< type >", "class_flaming_torch_1_1_disposable_pointer.html", null ]
    ] ]
];