Flaming Torch Framework: Gallant::detail Namespace Reference
Gallant::detail Namespace Reference
Classes
class ClosurePtr
struct DefaultVoidToVoid
struct DefaultVoidToVoid< DefaultVoid >
union horrible_union
struct SimplifyMemFunc
struct SimplifyMemFunc< SINGLE_MEMFUNCPTR_SIZE >
struct VoidToDefaultVoid
struct VoidToDefaultVoid< void >
Typedefs
typedef void DefaultVoid
Functions
template<class OutputClass , class InputClass >
OutputClass horrible_cast (const InputClass input)
template<class OutputClass , class InputClass >
OutputClass implicit_cast (InputClass input)
Variables
const int SINGLE_MEMFUNCPTR_SIZE = sizeof(void (GenericClass::*)())
Class Documentation
struct Gallant::detail::DefaultVoidToVoid
template<class T>
struct Gallant::detail::DefaultVoidToVoid< T >
Class Members
typedef T type
struct Gallant::detail::DefaultVoidToVoid< DefaultVoid >
template<>
struct Gallant::detail::DefaultVoidToVoid< DefaultVoid >
Class Members
typedef void type
union Gallant::detail::horrible_union
template<class OutputClass, class InputClass>
union Gallant::detail::horrible_union< OutputClass, InputClass >
Class Members
InputClass in
OutputClass out
struct Gallant::detail::VoidToDefaultVoid
template<class T>
struct Gallant::detail::VoidToDefaultVoid< T >
Class Members
typedef T type
struct Gallant::detail::VoidToDefaultVoid< void >
template<>
struct Gallant::detail::VoidToDefaultVoid< void >
Class Members
typedef DefaultVoid type
Typedef Documentation
typedef void Gallant::detail::DefaultVoid
Function Documentation
template<class OutputClass , class InputClass > OutputClass Gallant::detail::horrible_cast (const InputClass input) inline
References Gallant::detail::horrible_union< OutputClass, InputClass >::in, and Gallant::detail::horrible_union< OutputClass, InputClass >::out.
Referenced by Gallant::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::bindstaticfunc(), Gallant::detail::SimplifyMemFunc< SINGLE_MEMFUNCPTR_SIZE >::Convert(), and Gallant::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::GetStaticFunction().
template<class OutputClass , class InputClass > OutputClass Gallant::detail::implicit_cast (InputClass input) inline
Variable Documentation
const int Gallant::detail::SINGLE_MEMFUNCPTR_SIZE = sizeof(void (GenericClass::*)())