Flaming Torch Framework: Gallant Namespace Reference
Gallant Namespace Reference
Namespaces
detail
Classes
class Delegate0
class Delegate1
class Delegate2
class Delegate3
class Delegate4
class Delegate5
class Delegate6
class Delegate7
class Delegate8
class DelegateMemento
class Signal0
class Signal1
class Signal2
class Signal3
class Signal4
class Signal5
class Signal6
class Signal7
class Signal8
Functions
template<class X , class Y , class RetType >
Delegate0< FASTDLGT_RETTYPE > MakeDelegate (Y *x, RetType(X::*func)())
template<class X , class Y , class Param1 , class RetType >
Delegate1< Param1,
FASTDLGT_RETTYPE > MakeDelegate (Y *x, RetType(X::*func)(Param1 p1))
template<class X , class Y , class Param1 , class Param2 , class RetType >
Delegate2< Param1, Param2,
FASTDLGT_RETTYPE > MakeDelegate (Y *x, RetType(X::*func)(Param1 p1, Param2 p2))
template<class X , class Y , class Param1 , class Param2 , class Param3 , class RetType >
Delegate3< Param1, Param2,
Param3, FASTDLGT_RETTYPE > MakeDelegate (Y *x, RetType(X::*func)(Param1 p1, Param2 p2, Param3 p3))
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class RetType >
Delegate4< Param1, Param2,
Param3, Param4,
FASTDLGT_RETTYPE > MakeDelegate (Y *x, RetType(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4))
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class RetType >
Delegate5< Param1, Param2,
Param3, Param4, Param5,
FASTDLGT_RETTYPE > MakeDelegate (Y *x, RetType(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5))
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class RetType >
Delegate6< Param1, Param2,
Param3, Param4, Param5, Param6,
FASTDLGT_RETTYPE > MakeDelegate (Y *x, RetType(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6))
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class RetType >
Delegate7< Param1, Param2,
Param3, Param4, Param5, Param6,
Param7, FASTDLGT_RETTYPE > MakeDelegate (Y *x, RetType(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7))
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 , class RetType >
Delegate8< Param1, Param2,
Param3, Param4, Param5, Param6,
Param7, Param8,
FASTDLGT_RETTYPE > MakeDelegate (Y *x, RetType(X::*func)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8))
Function Documentation
template<class X , class Y , class RetType > Delegate0< FASTDLGT_RETTYPE > Gallant::MakeDelegate (Y * x, RetType(X::*)() func)
Referenced by Gallant::Signal0< Param0 >::Connect(), Gallant::Signal1< const std::vector< std::string > & >::Connect(), Gallant::Signal2< Param1, Param2 >::Connect(), Gallant::Signal3< const std::string &, const std::string &, uint32 >::Connect(), Gallant::Signal4< Param1, Param2, Param3, Param4 >::Connect(), Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Connect(), Gallant::Signal6< Param1, Param2, Param3, Param4, Param5, Param6 >::Connect(), Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Connect(), Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Connect(), Gallant::Signal0< Param0 >::Disconnect(), Gallant::Signal1< const std::vector< std::string > & >::Disconnect(), Gallant::Signal2< Param1, Param2 >::Disconnect(), Gallant::Signal3< const std::string &, const std::string &, uint32 >::Disconnect(), Gallant::Signal4< Param1, Param2, Param3, Param4 >::Disconnect(), Gallant::Signal5< Param1, Param2, Param3, Param4, Param5 >::Disconnect(), Gallant::Signal6< Param1, Param2, Param3, Param4, Param5, Param6 >::Disconnect(), Gallant::Signal7< Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Disconnect(), and Gallant::Signal8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8 >::Disconnect().
template<class X , class Y , class Param1 , class RetType > Delegate1< Param1, FASTDLGT_RETTYPE > Gallant::MakeDelegate (Y * x, RetType(X::*)(Param1 p1) func)
template<class X , class Y , class Param1 , class Param2 , class RetType > Delegate2< Param1, Param2, FASTDLGT_RETTYPE > Gallant::MakeDelegate (Y * x, RetType(X::*)(Param1 p1, Param2 p2) func)
template<class X , class Y , class Param1 , class Param2 , class Param3 , class RetType > Delegate3< Param1, Param2, Param3, FASTDLGT_RETTYPE > Gallant::MakeDelegate (Y * x, RetType(X::*)(Param1 p1, Param2 p2, Param3 p3) func)
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class RetType > Delegate4< Param1, Param2, Param3, Param4, FASTDLGT_RETTYPE > Gallant::MakeDelegate (Y * x, RetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4) func)
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class RetType > Delegate5< Param1, Param2, Param3, Param4, Param5, FASTDLGT_RETTYPE > Gallant::MakeDelegate (Y * x, RetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5) func)
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class RetType > Delegate6< Param1, Param2, Param3, Param4, Param5, Param6, FASTDLGT_RETTYPE > Gallant::MakeDelegate (Y * x, RetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6) func)
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class RetType > Delegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, FASTDLGT_RETTYPE > Gallant::MakeDelegate (Y * x, RetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7) func)
template<class X , class Y , class Param1 , class Param2 , class Param3 , class Param4 , class Param5 , class Param6 , class Param7 , class Param8 , class RetType > Delegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, FASTDLGT_RETTYPE > Gallant::MakeDelegate (Y * x, RetType(X::*)(Param1 p1, Param2 p2, Param3 p3, Param4 p4, Param5 p5, Param6 p6, Param7 p7, Param8 p8) func)